### PR TITLE
member.php: Add missing "mybb->" in resendactivation action

### PR DESCRIPTION
**Pull request by mytbk**

### CODE REVIEW

**Comment by Shade-** [comment]
`$mybb->user` refers to a logged in user; resendactivation is meant to be used by guests, so `$mybb->user['uid']` will always resolve to `0`, invalidating its purpose.

It's still a mystery to me where `$user` is declared. @mybb/developers @mybb/sqa

**Comment by effone** [comment]
Right. Its not declared for this action. So, after all there is a mistake.

**Comment by mytbk** [comment]
> $mybb->user refers to a logged in user; resendactivation is meant to be used by guests, so $mybb->user['uid'] will always resolve to 0, invalidating its purpose.

Hmm, I found this when I log in as an unactivated user and click the resend activation email link in usercp, then mybb gives an SQL error:

```
SQL Error:
0 - ERROR: invalid input syntax for integer: "" LINE 1: SELECT * FROM mybb_awaitingactivation WHERE uid='' AND type=... ^
Query:
SELECT * FROM mybb_awaitingactivation WHERE uid='' AND type='b'
```

**Comment by effone** [comment]
Resend activation link appears after login. So, by that time user obtains his UID.
I think this is a valid PR.

**Comment by Shade-** [comment]
Ah now I get it – indeed this will fix the issue.

**Comment by Shade-** [comment]
Thank you for your contribution! Next time, please open an issue before pushing a PR so it'll appear in the fixed issues list when we deploy new versions of MyBB.

**Comment by effone** [comment]
Related?
https://github.com/mybb/mybb/issues/2866

**Comment by Shade-** [comment]
Possibly. I'm not sure why `$user` is used if not declared.

**Comment by euantorano** [comment]
> Possibly. I'm not sure why $user is used if not declared.

Goodness knows, it's probably been that way for ages.

**Comment by effone** [comment]
Since a year, 1.8.12 (as per blame)
Not revealing the name though ...

**Pull request merged**
