### PR TITLE
Fixes #1770 Remove sessions from upgrade script

### LINKED ISSUE #1770: Remove sessions from upgrade script
This has caused some issues when upgrading to 1.8.x:
http://community.mybb.com/thread-162865.html
http://community.mybb.com/thread-161647.html
http://community.mybb.com/thread-163795-post-1124167.html
...

### PR DESCRIPTION
**Pull request by Stefan-ST**
Fixes #1770

### CODE REVIEW

**Comment by ATofighi** [comment]
I test it, it's don't work for me because `$mybb->user` isn't defined.

**Comment by Stefan-ST** [comment]
@ATofighi Oh, that was the reason for using sessions...
Unfortunately that means we need to copy some code since the session system always runs queries.

**Comment by ATofighi** [comment]
It still isn't OK :(
I see `You do not have permissions to run this process. You need administrator permissions to be able to run the upgrade procedure.` error when I login to my account in upgrade...

**Comment by Stefan-ST** [comment]
@ATofighi Wasn't a good solution though it worked for me...

Changing the session system is probably easier.

**Comment by Destroy666x** [comment]
Yeah, I think we should change the IP selection based on 1.4/1.6/1.8 version.

**Comment by ATofighi** [comment]
Merged.

**Pull request merged**
