### PR TITLE
Fix recaptcha v3 not working

### LINKED ISSUE #4458: Broken display and verification of reCAPTCHA v3 and Invisible hCaptcha
The CAPTCHA identifiers at
- https://github.com/mybb/mybb/blob/017922b902b76889a7b6e0595dfbc575613bacda/inc/class_captcha.php#L138
- https://github.com/mybb/mybb/blob/017922b902b76889a7b6e0595dfbc575613bacda/inc/class_captcha.php#L327
incorrectly point to `captcha::HCAPTCHA_INVISIBLE`, instead of `captcha::RECAPTCHA_V3`.

These result in:
- the wrong template being used for _reCAPTCHA v3_ and a broken _Image Verification_ prompt, and the possibility to bypass the CAPTCHA system when _reCAPTCHA v3_ is used
- the wrong handler used for verification of hCaptcha's Invisible Captcha (_hCaptcha invisible_), and rejection of all challenges for that system.

Regression from #4122

Reported in https://community.mybb.com/thread-233585.html

### PR DESCRIPTION
**Pull request by chack1172**
Resolves #4458 (https://community.mybb.com/thread-233585.html)

### CODE REVIEW

**Comment by Sama34** [comment]
The captcha is still not displayed for me.

**Comment by chack1172** [comment]
> The captcha is still not displayed for me.

It's an hidden  captcha, you will only see the captcha icon in the bottom right corner of the page.

**Review by Sama34 — APPROVED** [review]
Duh, I'm unsure how I did miss that (I even checked the page source code).

**Comment by MrOmnes** [comment]
Hello, that still not work for me even with replacing captcha.php

**Pull request merged**
