### PR TITLE
Fixes #2081 - Wrong label & tooltip for "New Posts" icon

### LINKED ISSUE #2081: Wrong label & tooltip for "New Posts" icon beneath "Subscribed Threads" list
Hi everyone!

I'm new to MyBB and this is my first post here, so: nice to meet you all.

I ran across this little glitch while working on a localization of MyBB 1.8.5. I ran a quick search of this forum and didn't find anything that seemed to match it, so I figured I'd better write it up. It's small, and probably easy to fix. 

To find the glitch, please navigate to User CP -&gt; Subscribed Threads and look at the icons displayed below the list. The topmost icon on the left reads "New Thread" where it should read "New Posts". (Compare the icons under the thread listing in any forum to see the difference.)

Basically, the label for the icon mentioned in the title seems to be using this string:

/inc/languages/english/usercp.lang.php =&gt; new_thread

... when it should be using this string:

/inc/languages/english/usercp.lang.php =&gt; new_posts_thread

The "new_thread" string is not a label, but text for a link that appears beneath each thread in the "Forum Subscriptions" list.

Which means I ended up with a translated icon label inviting me to create a new thread.  :P 

(EDIT: I originally included references to the "icon_*" strings, but I've since discovered that they're used in the tooltips for the icons in the actual thread list. I still find it puzzling that the tooltips for the icons in the legend simply repeat the labels; perhaps they should be removed?)

I hope this helps.

Cheers,
Dominion

The fix is a change to template "usercp_subscriptions" line 34:

Before:

Code:
&lt;dd&gt;&lt;span class="thread_status newfolder" title="{&#36;lang-&gt;new_thread}"&gt;&amp;nbsp;&lt;/span&gt; {&#36;lang-&gt;new_thread}&lt;/dd&gt;

After:

Code:
&lt;dd&gt;&lt;span class="thread_status newfolder" title="{&#36;lang-&gt;new_posts_thread}"&gt;&amp;nbsp;&lt;/span&gt; {&#36;lang-&gt;new_posts_thread}

Original thread: [Wrong label & tooltip for "New Posts" icon beneath "Subscribed Threads" list](http://community.mybb.com/thread-171921.html)

### PR DESCRIPTION
**Pull request by Cu8eR**
Wrong label & tooltip for "New Posts" icon beneath "Subscribed Threads" list

#2081

### CODE REVIEW

**Comment by Destroy666x** [comment]
This is absolutely not a valid fix.. You replaced a correct string with a blank string in a wrong template. As you can see in the issue, it's about User CP -> Thread subscriptions, not thread list.

**Comment by Cu8eR** [comment]
@Destroy666x 

Yes, you are right. I am sorry. Unfortunately, I cannot find the proper line where it should be changed :( I am be blind, could you or anybody please point me to the correct location? Thank you

**Comment by Destroy666x** [comment]
Well, you can easily find the template by going to UCP -> Subscribed threads and viewing the source code. It should be in `usercp_subscriptions` or something like that, IIRC.

**Comment by Cu8eR** [comment]
I am closing this... new PR is ready to merge #2258

**Pull request closed without merging**
