### PR TITLE
Add missing post keys to login forms

### LINKED ISSUE #3323: Missing `my_post_key` for login form in several places
As per https://community.mybb.com/thread-218460-post-1308277.html#pid1308277 the `my_post_key` input is missing in a couple of templates with login forms:

- [x] `error_nopermission`
- [X] `header_welcomeblock_guest`
- [X] `member_login`
- [x] `portal_welcome_guesttext`

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #3323

### CODE REVIEW

**Comment by AndreRl** [comment]
Looks fine, nicely done Euan.

**Comment by Eldenroot** [comment]
@euantorano - you added same code as I did before... so now it is doubled, please do not merge this until you change it... see my comment

**Comment by euantorano** [comment]
@Eldenroot You mean the template version changes or is there already a PR to add the `my_post_key`?

**Comment by Eldenroot** [comment]
Nope, you added the code to this template where I had added before

**Comment by euantorano** [comment]
Ah, I see what you mean: https://github.com/mybb/mybb/pull/3301

**Pull request closed without merging**
