### PR TITLE
Add closing `>` to fix typo in HTML tag

### LINKED ISSUE #4391: Missing HTML angle bracket in `post_attachments_new` template
The `post_attachments_new` template contains a typo where the `#dropzone > div` element's code is missing a `>` character in the opening tag at https://github.com/mybb/mybb/blob/mybb_1827/install/resources/mybb_theme.xml#L9471

Not known to be causing any issues.

Added in #4195

### PR DESCRIPTION
**Pull request by aitorres**
Resolves #4391

Adds a missing, closing `>` to an HTML tag (a div) that was previously unclosed.

---

First time contributing and it's a very, very minor thing. Let me know if there's anything else I can help with!

### CODE REVIEW

**Comment by euantorano** [comment]
The parent `<template>` XML tag will need it’s version number bumped, but otherwise nice work and thanks very much for your first contribution!

**Comment by aitorres** [comment]
Sure thing! I see that its current version is `1827`, is there any standard for what it should be bumped to? Or would just incrementing by one i.e. `1828` work?

**Comment by euantorano** [comment]
Just increment by 1 to 1828 please - we call these version codes and they’re basically version numbers without any dots (e.g. 1827 is 1.8.27).

**Comment by lairdshaw** [comment]
Didn't we decide not to accept PRs on the 1.8 branch after 1.8.27 was released, and only accept new PRs on the 1.9 branch once the rebase is up to date with 1.8.27?

**Comment by euantorano** [comment]
In essence, yes. However that doesn’t mean we can’t have PRs queued in case of a security fix. The plan is only fixes for major issues that break core functionality.

**Comment by lairdshaw** [comment]
OK, so where does that leave this particular PR? Is it a security fix?

**Comment by Ben-MyBB** [comment]
I believe the intention is that it a security release is required this fix can be released with.

**Comment by euantorano** [comment]
Yes, exactly as Ben said. If we have to release a hot fix release for a major breaking issue or a security issue, small fixes (and I do mean SMALL) can sneak in alongside them.

**Review by Ben-MyBB — APPROVED** [review]

**Comment by Ben-MyBB** [comment]
Thanks for your first contribution @aitorres :)

**Comment by lairdshaw** [comment]
> I believe the intention is that it a security release is required this fix can be released with.

Thanks for clearing that up - I see that I didn't understand Euan's comment. My fault, not his.

**Comment by Sama34** [comment]
I agree fixes like this could make it, more complex issues should be left for 1.9

**Review by Sama34 — APPROVED** [review]

**Pull request merged**
