### PR TITLE
Fixes #2223 - Add missing title tag for search_results_posts_post

### LINKED ISSUE #2223: Missing title tag for search_results_posts_post
Missing title tag for search_results_posts_post - add title tag for folder icon, much easier to see what the icon means.

This is already implemented for search_results_threads_thread

### PR DESCRIPTION
**Pull request by Cu8eR**
Add missing title tag for search_results_posts_post

title="{$folder_label}" is missing in this template; in  search_results_threads_thread is here

### CODE REVIEW

**Comment by Cu8eR** [comment]
@MyBB devs - sorry, I have no permissions to create an issue for this here...

**Comment by Destroy666x** [comment]
@Cu8eR where's an issue for this? Please create one if there is none or link to the issue next time.

Anyways, should be ok to merge after an issue is found/created.

**Comment by Cu8eR** [comment]
@Destroy666x - I am sorry, I cannot create new issues here on GitHub without your permissions, so I just created a PR with improvement. Now I created an issue here #2223

**Comment by Destroy666x** [comment]
Thanks.

**Pull request merged**
