### PR TITLE
Fixes #2756 $post['poststatus'] missing from postbit

### LINKED ISSUE #2756: $post['poststatus'] missing from postbit
The variable $post['poststatus'] is missing from the postbit templates. This variable is suppose to inform the moderator of the post's status (unapproved/soft deleted) and was missed when #1565 was added.

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2756

### CODE REVIEW

**Comment by JordanMussi** [comment]
Works as expected but I'm wondering why you hardcoded the `<em>` & `<strong>` in #2500 rather than giving the element a class to control the display?

**Comment by Cu8eeeR** [comment]
@JordanMussi - good catch, maybe we can create a separate PR for this

**Comment by euantorano** [comment]
This PR looks good to me, another PR to fix the hardcoded HTML as mentioned by @JordanMussi would be greta it anybody gets a chance.

**Comment by JordanMussi** [comment]
@euantorano fixed in #2784

**Pull request merged**
