### PR TITLE
Fixes #2047 Hello World plugin fails on SQLite and most likely also p…

### LINKED ISSUE #2047: Hello World plugin fails on SQLite and most likely also pgsql
Not good for an example plugin: http://community.mybb.com/thread-172178.html It should be compatible with our minimal requirements. I guess only the table creation query needs to be corrected,

### PR DESCRIPTION
**Pull request by PaulBender**
…gsql

Fixes #2047

### CODE REVIEW

**Comment by euantorano** [comment]
Sneaked that in whilst I was commenting there ;) Does uninstallation work correctly, there's some weird looking code relating to template/templateset deletion there.

**Comment by PaulBender** [comment]
Uninstalling works fine, but the code could be simplified.

**Comment by euantorano** [comment]
Would you have time to do that? If not, we can leave it as is if it's not causing problems.

**Comment by PaulBender** [comment]
Yeah, I can do it.

**Pull request merged**
