### PR TITLE
Fixes #2760

### LINKED ISSUE #2760: https support on help docs
Images of unsafe sources will be loaded on Mybb help docs.

### PR DESCRIPTION
**Pull request by SvePu**

### CODE REVIEW

**Comment by SvePu** [comment]
#2760

**Comment by Devilshakerz** [comment]
Thanks, can you also bump the version to `1813` in the [langauge manifest](https://github.com/mybb/mybb/blob/mybb_1812/inc/languages/english.php#L18)?

**Comment by PaulBender** [comment]
Also, you need to make the same change at this line:
https://github.com/mybb/mybb/blob/feature/install/resources/mysql_db_inserts.php#L44

**Comment by SvePu** [comment]
@Devilshakerz  & @PaulBender - THX for the hints...I changed both files

**Pull request merged**
