### PR TITLE
Fixes #1875 "Put the editor in source mode by default" ineffective when ...

### LINKED ISSUE #1875: "Put the editor in source mode by default" ineffective when previewing
The option "Put the editor in source mode by default" has no effect when you preview a post/thread.

### PR DESCRIPTION
**Pull request by Stefan-ST**
...previewing

Fixes #1875

This needs to be tested thoroughly.

### CODE REVIEW

**Comment by ATofighi** [comment]
Works good for me.

**Comment by Sama34** [comment]
@Stefan-ST did you updated to SCEditor 1.4.7?

**Comment by Stefan-ST** [comment]
@Sama34 Yes

**Comment by Sama34** [comment]
Shouldn't version be appended to `jquery.sceditor.bbcode.min.js` too then?

**Comment by Stefan-ST** [comment]
@Sama34 You are right. Fixed: 20c6b32fa5159bd5e15b6d556825b9af1f233f64

**Pull request merged**
