### PR TITLE
Update thread.js

### PR DESCRIPTION
**Pull request by ghost**
I had problem with quickedit feature, somehow it kept removing empty lines (<BR>) from pretty long, and quite bbcode formatted post. 
Adding this replace: pid = id.replace(/\n/gi, "<br>\n");, fixed the issue for me, might be worth investigating.

### CODE REVIEW

**Comment by ATofighi** [comment]
I don't test it, but think code is wrong! `id` can't have several lines. :-\

**Comment by jaszabb** [comment]
Well, it worked for me. (I don't use any mods which could have any influence on editing posts such as Advanced Quick Edit/Reply)

**Comment by ATofighi** [comment]
can I have your `postbit` and `postbit_classic` template?

**Comment by jaszabb** [comment]
postbit_classic: http://pastebin.com/BNUMkdrN
postbit: http://pastebin.com/ZBGzjB7P

And once again, it doesn't occur always, only for pretty long posts highly bbcoded.

**Comment by Destroy666x** [comment]
> Well, it worked for me.

There is no way `$("#quickedit_<br>\n_editreason")` would work properly.

Anyways, please report issues on our forum.

**Comment by jaszabb** [comment]
Destroy666x I don't know what you mean. 

This code solved a problem. I though i will share it with you, that's all. I usually don't report issues, because i can solve most of them myself.

**Comment by ATofighi** [comment]
your code === removing `pid = id.replace( /[^\d.]/g, '');`

**Comment by Destroy666x** [comment]
> This code solved a problem.

Would you mind explaining how and where does the `pid` variable affect post content? Also, I'd be grateful for an exemplary post which causes the bug. Thanks.

**Comment by Sama34** [comment]
If you could provide reproducible steps for a totally fresh MyBB installation, that would be nice. Even if this fixes an issue, we cannot merge it till we figure out it actually does so.

**Comment by ATofighi** [comment]
@ghost

**Comment by Destroy666x** [comment]
Closing this since the fix still doesn't make much sense and I can't even reproduce the issue.

**Pull request closed without merging**
