### PR TITLE
add {$collapsedthead['quickreply']}

### PR DESCRIPTION
**Pull request by Supryk**
added {$collapsedthead['quickreply']} to private_quickreply and showthread_quickreply

### CODE REVIEW

**Comment by Cu8eR** [comment]
#2485

**Comment by Cu8eR** [comment]
@Supryk - please, dont forget to increase the template version to 1809
https://github.com/Supryk/mybb/blob/e0cf0456004fb4f6d188c632bc362bf843196b23/install/resources/mybb_theme.xml#L10049

https://github.com/Supryk/mybb/blob/e0cf0456004fb4f6d188c632bc362bf843196b23/install/resources/mybb_theme.xml#L11505

**Comment by JN-Jones** [comment]
Apart from the mentioned issues this looks good. However I haven't tested this on any kind of board and haven't looked whether there are other collapsable items missing this kind of check.

**Comment by Cu8eR** [comment]
@Supryk - can you please fix this? Just change the template version to 1809, or if you cannot just contact me

**Comment by Supryk** [comment]
edited

**Comment by JN-Jones** [comment]
Thanks, I'll take a look later today or tomorrow if nobody beats me to it.

**Comment by Cu8eR** [comment]
@JN-Jones - should be fine

**Comment by JN-Jones** [comment]
@Ben-Conway can you take a look at this?

**Comment by JN-Jones** [comment]
Looks good, however I've noticed that the same issue applies to `showthread_threadnotes`. Can you fix that too @Supryk ?

**Comment by Ben-Conway** [comment]
@Supryk ? Or shall we just merge this?

**Comment by JN-Jones** [comment]
I planned to merge this and open a second issue if this PR isn't updated in time

**Comment by JN-Jones** [comment]
Merging

**Pull request merged**
