### PR TITLE
Fixes #3739 - replace hard coded values in ACP

### LINKED ISSUE #3739: Replace hard coded values in ACP
https://community.mybb.com/thread-223612.html

### PR DESCRIPTION
**Pull request by Eldenroot**
#3739

### CODE REVIEW

**Comment by euantorano** [comment]
I'm planning to review this today, sorry for the delay.

**Comment by yuliu** [comment]
Why has those two `Update management.php` not pushed into mybb:feature correctly? The latest `management.php` file has fatal errors as depict in [this community post](https://community.mybb.com/thread-223612-post-1331821.html#pid1331821).

@euantorano please have a check.

**Comment by Eldenroot** [comment]
@yuliu - please feel free to open a PR. My GitHub repo for MyBB feature is a pure mess, I need to wait until others PRs will be merged (finally) and start from scratch.

**Comment by euantorano** [comment]
I’m not sure what happened if this got messed up. I’m away from home for the rest of this week but will look into it as soon as I get a chance - probably this weekend.

**Comment by yuliu** [comment]
@Eldenroot, thanks for look into this. I think I could work out a solution tomorrow. Can probably imagine your trouble. :face_with_head_bandage: I have to hard reset my own MyBB repo every time the official one commits.

@euantorano, apology for that. I've edited my previous comment, so you won't receive the edited comment by email. I didn't tell the code differences with minor changes among commits at first. This pull itself doesn't mess up. But the resulting code does break MyBB forum management functionality. I'd like to submit a PR later and will just reference this PR and its original issue without creating a separated one. Also thanks for checking the message. Godspeed!

**Pull request merged**
