### PR TITLE
Fix #511 Calendar, Week Overview: Week period calculated wrong

### LINKED ISSUE #511: Calendar, Week Overview: Week period calculated wrong
calendar

As you can see, it tells me that the week has more than 2000 years :P (Note that the fix for #346 was applied on this board)

### PR DESCRIPTION
**Pull request by Devilshakerz**
#511

### CODE REVIEW

**Comment by JN-Jones** [comment]
This *should* work. However have you checked whether this (or a similar issue) may happen where we use `gmmktime`? Otherwise I'll make a short test about this tomorrow @Devilshakerz

**Comment by Devilshakerz** [comment]
It is used in other places but the dates there don't reach that far back, so it should be fine.

**Comment by JN-Jones** [comment]
@Ben-Conway can you take a look at this?

**Comment by JN-Jones** [comment]
As mentioned on slack: As we're casting the `week` parameter as int there are other issues on at least 32 bit systems. Eg my calendar only can go back till the 13.12.1901 as an integer can't go below that. However we still show links to go to the week before. Instead of simply casting it quietly we should either show a proper warning or hide the links. Note that I can't test the original error due to that limitation.

**Comment by Ben-Conway** [comment]
This looks good then.

**Pull request merged**
