### PR TITLE
Missing Colon

### LINKED ISSUE #3796: Missing colon
editpost and newthread templates.

Missing colon by Subject.

Original thread: [Missing colon](https://community.mybb.com/thread-223880.html)

### PR DESCRIPTION
**Pull request by Ben-MyBB**
Resolves #3796

### CODE REVIEW

**Comment by yuliu** [comment]
🤔 IIRC, colons following those lang entries need to be removed in newrhrad.php and editpost.php, or they could be in the templates.

**Comment by euantorano** [comment]
Agreed, punctuation should be in language files wherever possible.

**Comment by Ben-MyBB** [comment]
Thanks @yuliu . I have updated the additional instance you mentioned and pushed a new commit.

**Comment by Ben-MyBB** [comment]
Updated

**Pull request merged**
