### PR TITLE
Moves automatic URL replacement to the end of parsing.

### PR DESCRIPTION
**Pull request by lairdshaw**
Aims to fix the issues raised in the comments of #2968.
Supersedes #3103.

### CODE REVIEW

**Comment by euantorano** [comment]
This definitely seems like the better approach IMO. I assume we can close #3106 after I test and merge this?

I'm going to write some basic unit tests for the parser across today and tomorrow, though they'll only be in the 1.9 branch for now.

**Comment by labrocca** [comment]
Fix #3127 fixed my custom MyCode and appears to be working well.

**Comment by lairdshaw** [comment]
What's the protocol for changing PRs like this? I have a few amendments which also fix the problem I mentioned in #3067 - that of links potentially being replaced within existing links due to custom MyCodes. Should I file a separate PR noting that this one is superseded?

**Comment by lairdshaw** [comment]
Nvm. Figured it out. But feel free to edit the PR if you don't think the second commit belongs here.

**Comment by Sama34** [comment]
I'd let it be if it works. It would be perfect if you can share examples of what your PR fix so we can test it propertly. Currently there seems to be many discussion taking place in different PRs/issues. Thanks.

**Comment by euantorano** [comment]
Been doing some testing on this, and in my (very basic) tests it seems to be working exactly as it should - thanks a bunch @lairdshaw!

**Comment by Sama34** [comment]
The following also got fixed but I don't think it has an issue assigned to it.
https://community.mybb.com/thread-216948.html

**Comment by euantorano** [comment]
That’s a nice coincidence :)

**Pull request merged**
