### PR TITLE
Fixes #2371 - User activity in mod cp

### LINKED ISSUE #2371: Incorrect user activity when action is unset
At the moment if a Moderator is viewing the Mod CP homepage, on the Who's Online page their location is shown as "Viewing Reported Posts" rather than "Viewing Moderator CP".

The fix is rather simple, change [functions_online.php#228-232](https://github.com/mybb/mybb/blob/mybb_1807/inc/functions_online.php#L228L232) from:

``` php
            if(!isset($parameters['action']))
            {
                $parameters['action'] = 0;
            }
```

to:

``` php
            if(!isset($parameters['action']))
            {
                $parameters['action'] = 0;
                $user_activity['activity'] = "modcp";
                break;
            }
```

### PR DESCRIPTION
**Pull request by Cu8eR**
#2371

### CODE REVIEW

**Comment by Destroy666x** [comment]
I'm quite sure the fix is incorrect and the bug is somewhere else because this should take care of it: https://github.com/Cu8eR/mybb/blob/patch-4/inc/functions_online.php#L265-L268

**Comment by Destroy666x** [comment]
The cause is setting the parameter to 0, which doesn't make any sense and should be removed (or changed to empty string depending on ->). Also, either the empty check should be removed or the newly added lines. But the current `break` way is more optimal.

**Comment by Cu8eR** [comment]
OK, I understand. I will check it

**Comment by dequeues** [comment]
Any progress with this @Cu8eR?

**Comment by Cu8eR** [comment]
@dequeues - no, feel free to push your PR with fix.

**Comment by Destroy666x** [comment]
Ok, closing this then

**Pull request closed without merging**
