### PR TITLE
Fixes #3640 jQuery 3.3.1 + Compatibility Update

### LINKED ISSUE #2542: Update SCEditor
As mentioned elsewhere we should update SCEditor in 1.8.10. This will fix the following issues:

* #2045
* Probably #2112 
* #1674 
* Proper base for #2440 (may not be in the next version but the one after that)
* [Forum report](https://community.mybb.com/thread-173071.html) (https://github.com/samclarke/SCEditor/issues/545)

### LINKED ISSUE #2754: $sourcemode causes page to scroll to editor textarea when set to true via usercp.
When a user sets the option to show the MybbEditor in source mode by default ($sourcemode = "MyBBEditor.sourceMode(true);";) any page using it will scroll until the editor is in view. This causes issues on certain pages since the top of the page is not visible by default.

Checked in 1.8.11 on a test instance.

### LINKED ISSUE #3588: 1.8.20 Editor Center issue
Reproduction steps:
In message editor, center your text.

Preview your post OR send your message.

Notice that your text isn't centered anymore.

If you write align=center yourself, it works. If you use button for it, it doesn't.

Original thread: [1.8.20 Editor Center issue](https://community.mybb.com/thread-222153.html)

### LINKED ISSUE #3591: 1.8.20 sceditor font-size change bug
Hey,
since I updated MyBB to version 1.8.20 there is a display bug in the sceditor.

Steps to reproduce:
1. Write some words
2. mark one word and pick any color for font coloring
3. change font-size of the marked word
--> Font-size will be changed but the color switches back to black until I refresh the display by clicking "view source code" twice.

### LINKED ISSUE #3640: Upgrade jQuery to latest (3.3.1) & related js updates
Upgrade jQuery to latest (3.3.1) & related js updates
- Handle deprecated events
- Upgrade jEditable
- Upgrade SCEditor to latest

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #3640 
This also closes #2542, closes #2754, closes #3588 and closes #3591 

- [x] Upgrade jQuery 3.3.1.
Running Migrate console logger 3.0.1
Various compatibility code updates throughout templates / js files
---
- ~~Upgrade jEditable.~~ _Doesn't worth._
- [x] Upgrade jQuery Validation.
---
- [x] Upgrade SCEditor to 2.1.3:
- [x] Upgrade `bbcodes_sceditor.js` compatible with jQuery 3.3.1
- [x] Switch `bbcode` from plugin to format
- [x] Old missing themes & editor styles to fix / restore + custom command icons
- [x] Dropdown creator to point first node as per new syntax
- [x] `PHP` / `CODE` mixup issue

---
Known ignored deprecations:
- Usage of pseudo `expr[':']` in latest jquery.ui library
- Usage of `unique` in place of `uniqueSort` in latest jquery.ui library
- Various deprecated methods in jEditable
- Not in MyBB core but if some plugins script use `setInterval()` it will throw warning from jQuery core. Don't panic, ignore it.
https://github.com/jquery/jquery-migrate/pull/298
---
- [x] Final check + Version Bumps

### CODE REVIEW

**Comment by WildcardSearch** [comment]
@effone I will try to take a look tonight, if I get time.

**Comment by effone** [comment]
Its still under progress. I'll ping you when its finished.

**Comment by Eldenroot** [comment]
@MinusPL - as I saw your discussion and a thread with all known bugs in sceditor after last update, would be nice if you could test his PR and make a report :) thank you!

I will test myself, but I have not been using SCeditor for almost 3 years.

**Comment by effone** [comment]
## Important Note for Latest SCEditor Usage ##

- All the existing themes are required to `codebuttons` template **reverted to default**. This will not break any theme's style but there are critical parameter changes to take the SCE affect the input.

- As of SCE 2.1.3 the two existing themes `monocons` and `buttons` are dropped with a good logic that icon systems are not theme, they are part of theme. Instead an icon system has been implemented. The included icon system for now are `monocons` and `material`, so that you can use those icon systems with any theme.

- Considering the fact that the ACP is gonna be rewritten and uncertain future of SCE with MyBB; we are not including any option to choose for icon system. So attention vector icon lovers: You have to implement the icon system manually in `codebuttons` if you choose to use. The implementation is pretty simple and a snapshot can describe it all.
snap
Any further assistance - feel free to use [Community Forums Support Section](https://community.mybb.com/forum-176.html).

**Comment by MinusPL** [comment]
Tested all combination that came to my mind.
Editor seems to work properly.
Every issue that I wrote in my thread is resolved. So this change makes it work as it should.
Thanks for your work. 👍

**Comment by effone** [comment]
... and thank you sooo much for testing. Thats an even boring job. Thank you for taking all that pain and providing feedback.

**Comment by euantorano** [comment]
Excellent work @effone! Thanks so much for taking the time and effort.

**Comment by zAnonimo** [comment]
Hi, first of all, thanks a lot @effone for trying to fix this issue. As I told you in the MyBB's Discord, I'm testing this live in a large forum. Some errors started to appear to large threads, when the thread is really long, it seems to damage the style of the {posts} placeholder. Inspecting a lil bit the google chrome inspector, seems like most of the content gets out of `<div id="post_content">`.

Happens in default theme (I don't support the default theme so don't be afraid about missing images)
image

And my custom theme (modified Emerald)
image

Another think that I found out, is that SCEditor doesn't take the width of the screen properly. I have 1600x900 monitor and it allows me to expand the textbox to a maximum of 625width. I checked a lil bit .js file but didn't get any result (I'm not really used to javascript/jquery). This happens in both themes too.
image

This is all what I found so far. The SCEditor applies everything as it's supposed to do. Let me know if you can reproduce this errors and if not, I'll try to check further if it's a error in my side. Greetings!

**Comment by effone** [comment]
Do you have this setting in place (in `codebuttons` template):
`width: "100%",`
That should fix the width issue.

For the post breakage need to check the parsed code where it has happened and have to identify the defective element. Apparently it looks like a parser issue, not SCE.

**Comment by zAnonimo** [comment]
I added `width: "100%",` to my `opt_editor`. It didn't fix the width issue in my side. I really appreciate if you try to reproduce the parsing problem. Anyways, thanks a lot for your efforts! I'll be waiting for any fix :+1:

**Comment by effone** [comment]
Alright, I have inspected the 2 mentioned issues on site.
The width issue is not there with the setting in place. Its at your end and probably a CF cache issue.
The postbit breaking is entirely improper flex layout of your postbit, parser and SCE parse processes are fine.

**Pull request merged**
