### PR TITLE
Fixes #3427 Remove archive mode

### LINKED ISSUE #3427: Remove archive mode
The archive mode in 1.8 is mostly redundant and is built with hardcoded HTML. It can simply be removed for 1.9.

To remove:

- [x] `inc/functions_archive.php`
- [x] `inc/languages/english/archive.lang.php`
- [x] `archive/`
- [x] archive related settings
- [x] archive related permissions

This shouldn't have any effect elsewhere in the code, unless there are some re

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #3427

I believe I found all the bits related to the archive.

### CODE REVIEW

**Comment by chack1172** [comment]
Thank you Paul, I think there are other places where we should remove archive links.

**Comment by euantorano** [comment]
Found at least one more reference to archive:

- https://github.com/mybb/mybb/blob/develop/1.9/inc/src/Utilities/BreadcrumbManager.php#L118

**Comment by PaulBender** [comment]
I've removed it.

**Comment by WildcardSearch** [comment]
@PaulBender I'll be home in about twelve hours and I'll give this a look and try to get it merged (if Euan doesn't beat me to it)

**Pull request merged**
