### PR TITLE
ACP Group Join Settings UI Improvement

### LINKED ISSUE #3947: Checkbox in group settings doesn't work
I go to **ACP** > **Users & Groups** > **Groups**, and open any group I have created,
Than i go under "Publicly Joinable Options" and select "Yes, users must be invited in order to join this group" and when I click "Save user group" I get "The selected user group has been updated successfully." message. Until this point everything is okay, but the problem is that this checkbox didn't applied to group settings, so when I came back to chack settings, I saw that checkbox isn't selected. 
I tried this few times with few other groups and the issue is the same.

### PR DESCRIPTION
**Pull request by effone**
Resolves #3947

Added little flavor of js to improve ACP Group Join Settings avoiding confusion.

### CODE REVIEW

**Review by Sama34 — APPROVED** [review]
Since _Yes, all new join requests need to be moderated first_ and _Yes, users must be invited in order to join this group_ can't be active at the same time they should probably be radio buttons.

**Comment by effone** [comment]
A very good point @Sama34 but it is also possible for a user to only keep the option `Yes, users can freely join and leave this group` not opting in any of the second and third option.
So, in a scenario if either of the radio is selected already and user wants to **not** opt any of those (2nd and 3rd options) then in order to clear the already selected radio; user needs to first uncheck the first option -> save -> then again check the first option -> save again. Is it OK and acceptable?

Turning those to radio is easy, just a confirmation needed.

**Comment by dvz** [comment]
Group `type` options: https://github.com/mybb/mybb/issues/3818#issuecomment-542721458

Radio for types 2-5 should work well:
> 2: Disable join and leave options
3: Unrestricted
4: Moderate join requests
5: Invitation only

**Comment by Eldenroot** [comment]
Group type would beusable too, it depends what do you prefer :)

**Comment by effone** [comment]
4 radios sound good.

**Comment by Sama34** [comment]
@effoce you could hide one field when the other is selected, that could be enough?

**Comment by Eldenroot** [comment]
The first or the second one... both are better than it is right now :)

**Comment by Sama34** [comment]
Just to clarify, if you want to improve it I will review again but I'm fine with the PR as is.

**Comment by Eldenroot** [comment]
It should be fine, briefly tested.

**Comment by effone** [comment]
I'm gonna push a new PR shortly, non-js radio control only.
We can compare and adapt the best ...

**Comment by Eldenroot** [comment]
OK, that would be great!

**Comment by Ben-MyBB** [comment]
@effone just a reminder about the extra PR when you get a chance

**Comment by effone** [comment]
OK, give me some times now and I'll do it.

**Comment by Eldenroot** [comment]
This one should be finished, rejected or merged.

**Comment by Sama34** [comment]
If someone wants to improve this please send a PR.

**Pull request merged**
