### PR TITLE
Fixes #4773 - Improve 2FA QRCode presentation

### LINKED ISSUE #4773: Improve 2FA QRCode presentation
https://community.mybb.com/thread-239405.html

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #4773

### CODE REVIEW

**Comment by Sama34** [comment]
Would it be reasonable to add a language string for this ?

**Comment by Eldenroot** [comment]
Is it needed?

**Comment by Sama34** [comment]
I would think so, for non Latin-alphabet based languages the most.

**Comment by Eldenroot** [comment]
I am still not sure, there is almost nothing to translate...

**Pull request merged**
