### PR TITLE
Remove ICQ

### LINKED ISSUE #4816: Remove ICQ field
ICQ will be shut down on June 26.
Source: https://icq.com/desktop/de#windows

### PR DESCRIPTION
**Pull request by effone**
Resolves #4816

### CODE REVIEW

**Comment by Sama34** [comment]
Maybe we would be better off holding this for 1.9 ? It might be possible administrators would dislike losing this data in a minor update, it seems an abrupt change considering it can be simply disabled by default instead for 1.8

**Comment by Stefan-MyBB** [comment]
It makes little sense to keep the data as it has simply become useless. The field is not removed because ICQ has lost importance, but because it has been shut down for good.

**Comment by dvz** [comment]
It could be that some translations/boards repurpose the field for more relevant/local equivalents.

**Comment by Stefan-MyBB** [comment]
AIM and Yahoo have been removed in a minor updates: #3199 #3695

**Comment by Sama34** [comment]
This seems to affect the merge system. Next time, I think we should stick to keeping fields in the DB and drop them later in major versions.

**Pull request merged**
