### PR TITLE
Fix #2517 Invalid values used with operators expecting numbers raise E_WARNING on PHP 7.1

### LINKED ISSUE #2517: Invalid values used with operators expecting numbers raise E_WARNING on PHP 7.1
https://github.com/mybb/mybb/blob/mybb_1808/inc/functions_calendar.php#L453-L461
https://github.com/mybb/mybb/blob/mybb_1808/calendar.php#L1536-L1545
`$offset` can be empty or non-numerical; more files can be affected.

http://php.net/manual/en/migration71.other-changes.php

### PR DESCRIPTION
**Pull request by Devilshakerz**
#2517

### CODE REVIEW

**Comment by Matslom** [comment]
Found this https://github.com/mybb/mybb/blob/f6e6cadccc9ed94b5324bb57aff7fe3f3f48999f/global.php#L927 If I'm not mistaken it should be also casted as float.

**Comment by Ben-Conway** [comment]
@Devilshakerz ?

**Comment by Devilshakerz** [comment]
Updated

**Comment by Ben-Conway** [comment]
Thanks @Devilshakerz !

**Comment by Matslom** [comment]
Looks ok for me.

**Comment by Ben-Conway** [comment]
Did you actually test this or just look at the code @Matsolm ?

**Comment by Matslom** [comment]
I tested it also.

2017-01-08 11:08 GMT+01:00 Ben C <notifications@github.com>:

> Did you actually test this or just look at the code @Matsolm ?
>

**Pull request merged**
