### PR TITLE
Fixes #2104 ACP rebuilding thumbnails ignores uploadpath

### LINKED ISSUE #2104: ACP rebuilding thumbnails ignores uploadpath
PHP Code:
&#36;thumbnail&nbsp;=&nbsp;generate_thumbnail(MYBB_ROOT."uploads/".&#36;attachment['attachname'],&nbsp;MYBB_ROOT."uploads/",&nbsp;&#36;thumbname,&nbsp;&#36;mybb-&gt;settings['attachthumbh'],&nbsp;&#36;mybb-&gt;settings['attachthumbw']);&nbsp;

As you can see that code expects the attachment to be in the default directory. However we have a setting for that (&#36;mybb-&gt;settings['uploadspath'])

Original thread: [ACP rebuilding thumbnails ignores uploadpath](http://community.mybb.com/thread-172188.html)

### PR DESCRIPTION
**Pull request by JN-Jones**
#2104

### CODE REVIEW

**Comment by Destroy666x** [comment]
The default path is `./uploads` and I don't think that works with `MYBB_ROOT` in front, correct me if I'm wrong

**Comment by JN-Jones** [comment]
You can have pathes mixed like this: `/dev/upload/./uploads`, the merge system does that all the time.

**Comment by JN-Jones** [comment]
@Destroy666x @euantorano

**Comment by Destroy666x** [comment]
You're right, it seems to be fine.

Also noticed another small issue - if the path is `../something`, System Health detection is broken due to this line: https://github.com/mybb/mybb/blob/feature/admin/modules/tools/system_health.php#L853 which becomes invalid `.../something`. It should be either `"../{$mybb->settings['uploadspath']}"` or `MYBB_ROOT.$mybb->settings['uploadspath']` - would be nice to fix it here.

**Comment by JN-Jones** [comment]
Yeah, that line should use `MYBB_ROOT` too. Not sure whether we support anything except relative pathes, need to recheck that, otherwise checking whether the setting starts with a `.` should be enough.

**Comment by JN-Jones** [comment]
Upated the `uploadspath` and `avataruploadpath` checks. Also added checks for absolute pathes.

**Comment by JN-Jones** [comment]
@Destroy666x @euantorano @PaulBender

**Comment by JN-Jones** [comment]
@mybb/developers

**Comment by JN-Jones** [comment]
Bump

**Comment by JN-Jones** [comment]
Bump

**Comment by PaulBender** [comment]
Works fine for me

**Pull request merged**
