### PR TITLE
Fixes #4111 - Inconsistent capitalization in online.php

### LINKED ISSUE #4111: Inconsistent capitalization in online.php
Hello,

In: /online.php
If user is rating thread is: Rating thread
If user is reading thread is: Reading Thread
[attachment=43050]

This is not a serious mistake, but I think the capitalization can be standardized.

Original thread: [Inconsistent capitalization in online.php](https://community.mybb.com/thread-228516.html)

### PR DESCRIPTION
**Pull request by Ben-MyBB**
Resolves #4111

### CODE REVIEW

**Comment by JordanMussi** [comment]
I wonder if now is a good time to do some of the others too, eg warnings: https://github.com/mybb/mybb/pull/4112/files#diff-baa01bd6316f876fbbcb5dfa4234f868R125-R128 revoking_warning etc & search_for_user

**Comment by yuliu** [comment]
Why not change all of them, except the initial, to lower case..

**Comment by Ben-MyBB** [comment]
I think if there's other inconsistencies they should be fixed in a seperate issue since this one is aimed at the online.php problem.

**Comment by euantorano** [comment]
Yes, I would prefer lots of smaller PRs over one massive PR.

**Pull request merged**
