### PR TITLE
Fixes #1567 It's impossible to send a PM to a user with a short username

### LINKED ISSUE #1567: It's impossible to send a PM to a user with a short username
If a username is shorter than 3 characters it impossible to send him a PM because Select2 doesn't accept anything that short.

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #1567

- Shortens minimumInputLength to ~~1~~ 2
- Removed maximumSelectionSize on all select2 that aren't multiples
- Tied maximumSelectionSize to maxpmrecipients for PMs
- Centralized select2 placeholder language strings to the global language file (pointless to keep the same string scattered across 7 language files)

### CODE REVIEW

**Comment by Stefan-ST** [comment]
I don't think minimumInputLength shouldn't be 1. It makes not much sense to display suggestions after one or two entered characters because there are probably too many matches (and it only displays 15?).

**Comment by PaulBender** [comment]
Should minimumInputLength be 2 then?

**Comment by Cu8eR** [comment]
I suggest 2

**Comment by PaulBender** [comment]
Okay, I've increased it to 2.

**Comment by JN-Jones** [comment]
Can anybody check this? Would be good to have this in 1.8.6

**Comment by euantorano** [comment]
I'll try and test this tomorrow night if I get time.

**Comment by PaulBender** [comment]
We should get this merged.

**Comment by euantorano** [comment]
Tried and tested, seems to work fine for me. Merging.

**Pull request merged**
