### PR TITLE
More flexible styling for postbit_status

### PR DESCRIPTION
**Pull request by JordanMussi**
Fixes comment here: https://github.com/mybb/mybb/pull/2757#issuecomment-312932548

### CODE REVIEW

**Comment by euantorano** [comment]
Not yet tested this, but have looked at the changes. Does this retain the same styling as it previously had?

**Comment by JordanMussi** [comment]
Um, it has the same style as the IP logged text. Do you want strong italics added?

**Comment by euantorano** [comment]
Probably for the best to have it match how it currently looks if possible :smile:

**Comment by JordanMussi** [comment]
This wasn't being displayed in previous releases so there isn't a currently 😛 - I'm just not sure about having such heavy emphasis on the text.

**Comment by euantorano** [comment]
Ah, fair enough. Might as well leave it as is then.

**Pull request merged**
