### PR TITLE
Upgrade SCEditor to 1.5.2

### LINKED ISSUE #3554: Smilie select is not working
The smilie selector box when creating a thread is not working. The following error is logged in the console:

```
TypeError: null is not an object (evaluating 'MyBBEditor.insertText')
```

`MyBBEditor` is indeed null.

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #3554.

This is the final 1.x release of SCEditor. 2.x has a lot more changes that would require much more work to upgrade to and has more chance of breakage.

### CODE REVIEW

**Comment by dvz** [comment]
The [`mybb.css` theme](https://github.com/mybb/mybb/blob/feature/jscripts/sceditor/editor_themes/mybb.css) will need updating too, as some positions in https://github.com/mybb/mybb/blob/feature/jscripts/sceditor/editor_themes/famfamfam.png have changed.

**Comment by euantorano** [comment]
Great. I’ll try find time to do so this week.

**Comment by euantorano** [comment]
@dvz `mybb.css` updated, but I don't have time to test - I've based the changes on looking at the updated image and the CSS class names.

**Comment by martec** [comment]
hi,

for me need updating too other theme present like monocons.css

**Comment by euantorano** [comment]
Monocons is updated by this PR as it is supplied by SCEditor. Maybe you need to empty your cache?

**Comment by martec** [comment]
what i trying say it's need make same type of update of mybb.css for all other theme of editor.
like /* Additonal buttons (for MyBB) */ that now missing.

check link below.

https://github.com/mybb/mybb/commit/6d4ee30faa3c108a89fd844f19bc026cad5c0c65#diff-ae7ae50d9bd045d21fdbebf86a57538aL698

**Comment by euantorano** [comment]
Oh, yeah good catch. I’ll open a PR tonight to add that. Thanks!

**Comment by martec** [comment]
You're Welcome

**Pull request merged**
