### PR TITLE
Fixes #2629 Group promotions bug

### LINKED ISSUE #2629: Group promotions bug
(told to post here by Euan T)

Upon editing a group promotion for registered length, and then revisiting the group promotion then the entry that you insert changes to something else. For example, from 2 months to 2 days. In the database, the entry is "=" (see below screenshots) I have confirmed this across three sites: 
https://creatorswave.com/ https://forumauthority.com/ and https://www.atlasindustries.info/forum/
These sites are: 1.8.9(Creators Wave and Forum Authority) and 1.8.10(Atlas Industries)

SQL code on the updating of group promotions
Code:SET `title`='Legend', `description`='Became a Legend', `posts`=10000, `posttype`='&gt;', `threads`=0, `threadtype`='&gt;', `registered`=100, `registeredtype`='=', `online`=10, `onlinetype`='years', `reputations`=0, `reputationtype`='&gt;', `referrals`=0, `referralstype`='&gt;', `warnings`=0, `warningstype`='&gt;', `requirements`='postcount,threadcount,reputation,referrals,warnings,timeregistered,timeonline', `originalusergroup`='12', `newusergroup`=16, `usergrouptype`='primary', `enabled`=1, `logging`=1 WHERE pid = '11'

notice how registered type is still = while onlinetype works just fine.
The registertypes that have "months" were manually adjusted through the database. While the ones with = were saved from the admincp. Even if you edit it in the database and then you make an adjustment from the admincp and save... it'll change it back to =

Original thread: [Group promotions bug](https://community.mybb.com/thread-207494.html)

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2629 

Created a separate check for the time fields.

### CODE REVIEW

**Comment by euantorano** [comment]
@katosdev Since you were encountering this issue, any chance you can check if this patch resolves your issue?

**Comment by katosdev** [comment]
Yep. I'll have a look when I'm home. Cheers both 

@euantorano @PaulBender

**Comment by katosdev** [comment]
Tested and confirmed working on Atlas Industries @euantorano @PaulBender cheers both

**Comment by katosdev** [comment]
Credits to: @suraf for confirming the bug.

**Comment by Ben-Conway** [comment]
Merging then.

**Pull request merged**
