### PR TITLE
Add "Mark site as read" into footer (#1583)

### PR DESCRIPTION
**Pull request by Cu8eeeR**
First commit for #1583

@MyBB devs - it would be nice to have more improvements from the list
added in 1.8.9 release. At least for the front-end part. Many of the proposed changes are really nice and useful.

@Destroy666x @Stefan-ST @JN-Jones @JordanMussi @Ben-Conway @PaulBender  and others

### CODE REVIEW

**Comment by Shade-** [comment]
You should also remove the old link in `index_boardstats`: [L4335](https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L4335).

Possibly, the lang variable `markread` should be used instead of adding a new one which may look redundant.

**Comment by Cu8eeeR** [comment]
@Shade- - yeah, thank you. I will edit my PR later today

**Comment by Cu8eeeR** [comment]
OK, I changed the lang string to the existing one. 

I am not sure about removing the old link from board stats, it looks fine for me. Anyway, tell me I will change it if you wanna.

**Comment by Shade-** [comment]
The fact is - if you add something to the footer, it will be displayed on the index which already displays the same link under the index_boardstats template. That's why I feel like it should be removed.

**Comment by MyBB-Andro** [comment]
Agreed with @Shade-

I don't see any reason to keep it under board stats as it would be
available under footer for every pages.

**Comment by Cu8eeeR** [comment]
Well, then it is illogical to have log out/board team links under board stats. Maybe it requires complex changes

**Comment by Ben-Conway** [comment]
I don't feel that this is needed at this stage in 1.8, we should be focussing on the back log of issues we have? @JN-Jones @euantorano

**Comment by Cu8eeeR** [comment]
@Ben-Conway - I agree, anyway some of the suggested improvements in #1583 are nice and useful. However I know that there are more important bugs to fix :)

**Comment by JN-Jones** [comment]
Basically agreed but as we have a PR I'm fine with testing this at a later point.

**Comment by MyBB-Andro** [comment]
@JN-Jones Have you tested it?

**Comment by JN-Jones** [comment]
No, if I test an issue I post my results so please stop poking me everyday

**Comment by JN-Jones** [comment]
`$lang->markread` isn't loaded globally so it isn't working

**Comment by Cu8eeeR** [comment]
@JN-Jones - ok, I will fix it ASAP. I just wanna know if you wanna include this PR or not. I am just not sure about this change... :(

**Comment by Ben-Conway** [comment]
I guess we could include it in 1.8.9 @JN-Jones ?

**Comment by JN-Jones** [comment]
Not 1.8.9 but 1.8.10 likely. Depending on how fast a fix will come.

**Comment by Matslom** [comment]
So this line https://github.com/mybb/mybb/blob/feature/inc/languages/english/index.lang.php#L16 should not be deleted?

**Comment by Cu8eeeR** [comment]
There are still two uncompleted things:
- remove unused lang string
- remove link from board stats

I will fix it soon (at work now, I had some spare time so I tried to fix them all at once)

**Comment by Ben-Conway** [comment]
@euantorano Do we want to include this one?

**Comment by euantorano** [comment]
I think at this point it’ll be 1.8.11 before it makes it in.

**Comment by Ben-Conway** [comment]
The code looks correct to me?

**Comment by euantorano** [comment]
Apart from the template version needing bumped to `1810`, yes. If I get time to test it, I will.

**Comment by Ben-Conway** [comment]
@Cu8eeeR Can you edit the template version?

**Comment by Ben-Conway** [comment]
@euantorano template number updated

**Comment by Stefan-ST** [comment]
There are 2 issues with this PR: https://github.com/mybb/mybb/commit/3ed92adcc1338a31330a2ba294aa2385d0c60083#commitcomment-20406009

**Comment by Stefan-ST** [comment]
PR: #2609

**Comment by Cu8eeeR** [comment]
@Stefan-ST @Ben-Conway 

I am sorry guys but here in Europe I am at work all the day :( Thank you for fixing these issues!

**Pull request merged**
