### PR TITLE
While soft deleting threads, now its posts are also removed.

### LINKED ISSUE #4083: Posts in unviewable threads appear in search
In my forum users recently noticed that they can see user's messages in removed thread when they search for their posts. I could confirm this happening even after I moved thread to another forum - to see if it's permission issue or not. It seems that post search feature doesn't check if that post is located in removed thread.

Original thread: [Post search doesn't check if thread is removed](https://community.mybb.com/thread-224436.html)

### PR DESCRIPTION
**Pull request by rajat315315**
Resolves #4083 

For soft_delete_thread requests, posts are also deleted now, so they won't appear in search results.

### CODE REVIEW

**Comment by yuliu** [comment]
Hmm, I don't think the root cause of #4083 is how soft delete works.

**Comment by rajat315315** [comment]
When a thread is soft deleted, it should delete its replies also.
It was not happening earlier.

**Comment by Ben-MyBB** [comment]
This would mean that if a thread is soft deleted and then restored, all replies to the thread will be hidden unless they are also restored. I don't believe that could be coded in to this fix because you may intentionally deleted one post on the thread already.

I haven't looked at the code yet for the search, but I was thinking that it wasn't checking if the post is soft deleted in that location?

**Comment by rajat315315** [comment]
Yeah, that's true. I agree. Haven't thought about deleting and restoring part.

**Comment by Eldenroot** [comment]
Also you have two fixes in one PR, you should create branches for every PR (fix).

For this issue, you have to check if the thread is deleted or not and then apply to posts...

**Comment by yuliu** [comment]
> I think when a thread is soft deleted, it should delete its replies also.

Hmm, that's not true IIRC. Currently when a thread is soft-deleted only the thread is marked and none its posts will be marked, and that's why it's called thread soft-deleted not posts soft-deleted. Other modules should check if a thread is marked as soft-deleted but not by its posts.

> But what was happening is :
> Variable "visible" remained set to 1 for the replies of soft_deleted threads, so even though they didn't appear to be deleted, they appeared in search.

That's because the code in search.php isn't doing right. Please see https://github.com/mybb/mybb/issues/4083#issuecomment-648744802 .

**Pull request closed without merging**
