### PR TITLE
Fixes #4334 #4336 - PM - icons/posticons/check boxes are misaligned + bgcolor for trows is used

### LINKED ISSUE #4334: UCP-PM - icons/posticons/check boxes are misaligned
Original thread: [UCP-PM - icons/posticons/check boxes are misaligned](https://community.mybb.com/thread-231753.html)

### LINKED ISSUE #4336: UCP-PM - bgcolor is not used, trow1/2 are vertically not horizontally
image

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #4334 

Resolves #4336 

EDIT: Fixes both issues :)

### CODE REVIEW

**Comment by Eldenroot** [comment]
image

**Comment by effone** [comment]
As you have touched the template; let me mention here that the way `trow` is added in the template is not the standard style of MyBB. It is creating vertical stripes in place of horizontal.

**Comment by effone** [comment]
Pushed the changes to match with MyBB style. Hope you don't mind.

**Comment by Eldenroot** [comment]
Completely fine, thank you!

**Review by Ben-MyBB — APPROVED** [review]

**Pull request merged**
