### PR TITLE
Fixes #2765 - explicit declaration for error array

### LINKED ISSUE #2765: $errors array needs explicit declaration in member.php
Since PHP 7.1, arrays need explicitly declaring; you can no longer implicitly cast an empty string to an empty array.

Quote:As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array.
(http://php.net/manual/en/language.types.array.php)

In member.php, line 255 causes an error if the Captcha test fails. It assumes &#36;errors is already an array.

We need to replace (line 205)

PHP Code:&#36;errors&nbsp;=&nbsp;"";&nbsp;
with

PHP Code:&#36;errors&nbsp;=&nbsp;array();&nbsp;

Original thread: [$errors array needs explicit declaration in member.php](https://community.mybb.com/thread-210918.html)

### PR DESCRIPTION
**Pull request by Cu8eeeR**
#2765

### CODE REVIEW

**Comment by Cu8eeeR** [comment]
@Devilshakerz - I sent a new PR. Somehow it shows changes in lines which were untouched. GitHub bug?

**Comment by Devilshakerz** [comment]
In the changed lines the encoding was changed from CRLF to LF (good - apparently there were some remaining ones in the core), however line 1344 was duplicated for some reason.

**Comment by chack1172** [comment]
File: member.php
Line: 1345
You duplicated a line

**Comment by Cu8eeeR** [comment]
@Devilshakerz @chack1172 - FIXED! :)

**Comment by Cu8eeeR** [comment]
This fix is not a proper fix (needs more changes...). Moreover GitHub makes me crazy with autochanging encoding.

**Pull request closed without merging**
