### PR TITLE
Fixes #2130 can not set permissions on another super admin

### LINKED ISSUE #2130: can not set permissions on another super admin
I was super admin on my website. when trying to change the permissions of other super admin, the following warning appears as shown in the picture. 

[attachment=32831]

[attachment=32833]

how to fix this problem in MyBB 1.8?  :S 

because I also have added a user ID into config.php  :-/

Original thread: [can not set permissions on another super admin](http://community.mybb.com/thread-161704.html)

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2130

### CODE REVIEW

**Comment by Destroy666x** [comment]
The functionality is still inconsistent across pages though:
- the users module let's you update another super admin if you're a super admin https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L440
https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L1708
https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L1910
https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L2771
- the admin permissions module doesn't let you update super admins at all, even if you want to edit your own permissions...
https://github.com/mybb/mybb/blob/feature/admin/modules/user/admin_permissions.php#L113
https://github.com/mybb/mybb/blob/feature/admin/modules/user/admin_permissions.php#L46

It doesn't make much sense. You can for example merge a super admin with another account which is not super admin and then edit  permissions.

**Comment by JN-Jones** [comment]
I think we should discuss a proper solution on the issue ticket before we do any code related changes and introducing more inconsistent behavior.

**Comment by Ben-Conway** [comment]
I don't see why you would want to set permissions on another super administrator, if you can't trust them to have full access to the acp they shouldn't be a super admin.

**Comment by PaulBender** [comment]
Either way, this should be merged as it corrects the error message.

**Comment by Ben-Conway** [comment]
Good work @PaulBender, just noticed this fixed the error message.

**Pull request merged**
