### PR TITLE
Hi, I'm making updates for Open Collective. Either you or a supporter…

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
… signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/mybb ❤️

It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

Thank you for your great contribution to the open source community. You are awesome! 🙌
And welcome to the open collective community! 😊

Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

I recognize that this PR is not in keeping with your Contributing guidelines that suggest an issue should be made through the forum and then pulled. However, this change is to the readme and not to the code.

### CODE REVIEW

**Comment by euantorano** [comment]
Looks good to me, any other feedback before I merge this @mybb/management @mybb/designers @mybb/developers @mybb/community-team?

**Comment by justinsoltesz** [comment]
Looks good to me. We will need to update the donate page on the website as well, but that will be easy enough.

**Comment by euantorano** [comment]
Do we want to schedule that to go live at the same time then @justinsoltesz? You'll also need to duplicate the changes to the new design unless we plan to roll that out soon?

**Comment by justinsoltesz** [comment]
I can get that page updated tonight (in both the live site and the new site) and merge this pull request then.

**Comment by euantorano** [comment]
Sounds good to me, thanks Justin!

**Pull request merged**
