### PR TITLE
banuser breadcumb fix

### PR DESCRIPTION
**Pull request by Gyaviste**

### CODE REVIEW

**Comment by Sama34** [comment]
Can you link us to the issue or forum thread? Also, please remove the extra space added in the first modified line.

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/issues/2414
Except the redundant spacing the fix is ok.

**Comment by Sama34** [comment]
@dequeues did you removed the spacing?

**Comment by dequeues** [comment]
Yeah https://github.com/mybb/mybb/commit/d784b4556f605169061b5a160340630b3c7b66a5

**Pull request merged**
