### PR TITLE
Fixes #1804 bugged icon positioning in sprite

### LINKED ISSUE #1804: Bugged icon positioning in headerlinks_sprite.png
This problem affects two files:
* `mybb/images/headerlinks_sprite.png`
* `mybb/install/resources/mybb_theme.xml`

In short, those icons are not centered relatively to text.
przechwytywanie

We need to add a following line line to `#logo ul.top_links`:
```css
line-height: 16px;
```

But now bell icon is cropped at bottom:
przechwytywanie

Bell icon has following CSS:
```css
#logo ul.top_links a.portal {
    background-position: 0 -180px;
}
```
All icons in this sprite are 16x16, but this single one is shifted 2px to bottom. I marked 16x16px square with red color, and blue line is set at position -180px.

przechwytywanie

As you can see, bell icon is wrongly positioned.
After fix, it's going to look fine:

przechwytywanie

Edit: sorry for commits spam, I had trouble with putting tabulator in CSS. My editor replaced it with 4 spaces... I created pull request with correct commit.

### PR DESCRIPTION
**Pull request by stil**

### CODE REVIEW

**Comment by Cu8eR** [comment]
Looks good to me!

**Comment by Destroy666x** [comment]
@stil, you could also remove the unused transparent background at the bottom of the sprite.

**Comment by stil** [comment]
5 bytes less in file size doesn't make any difference.

**Comment by Cu8eR** [comment]
make it properly when you have already spent time for fixing this :)

**Comment by Destroy666x** [comment]
> 5 bytes less in file size doesn't make any difference.

Correcting icon position by one pixel doesn't make much difference for me either, but I don't say it's not worth including it. Cutting off the bottom is a very simple change, so I don't see why not to save these "5 bytes" when you have already done other modifications to the file.

**Comment by Cu8eR** [comment]
@stil - could you fix this PR?

**Pull request merged**
