### PR TITLE
Suggestion for PM Folders

### PR DESCRIPTION
**Pull request by Xazin**
This PR creates a 'delete' button below removable folders inside _Edit Folders_ in the Private Messaging Panel. 

The function rebuilds the folders without the _folder id_ in question, and deletes all private messages in that folder.

Added a preview to show how the button looks.
HyT6sX6

### CODE REVIEW

**Comment by Xazin** [comment]
Also, inside compose, tracking and edit folders, the folder specific navigation is missing. Might add it to this PR.

**Comment by Xazin** [comment]
I've injected `$folders` such that folders are in navigation whilst viewing compose, tracking and edit folders.

**Comment by euantorano** [comment]
Note: I'm not ignoring this, but will merge it at a later date.

**Comment by Xazin** [comment]
Will resolve merge conflicts.

@euantorano , can you take a quick look and let me know if there are any changes you want here as well?

**Comment by Xazin** [comment]
@euantorano Resolved conflicts.

I saw that there are predefined 5 empty text fields to add new folders, seem quite redundant? Why not just have an add more option to add a new text field option? Opinion?

**Pull request closed without merging**
