### PR TITLE
fixes #4527

### LINKED ISSUE #4527: Add new plugin hook "admin_user_users_edit_overview_table" into admin/modules/user/users.php
To have possibility of adding new entries into acp user overview table, ~~move the plugins hook "admin_user_users_edit_overview" up~~ add a new plugin hook "admin_user_users_edit_overview_table" before outputting the table and make avatar cell row span variable.

acp_overview_user

### PR DESCRIPTION
**Pull request by SvePu**
Resolves #4527

### CODE REVIEW

**Comment by lairdshaw** [comment]
PRs like this should generally be applied to the `dev-1.9` branch. The 1.8 branch is only being updated for major security issues. Given its small size, though, it's possible that this patch would be merged during any potential future security release.

**Comment by SvePu** [comment]
@lairdshaw Thx for the info ... I've tried to change the pr base but it looks like being conflicts with this action. Next one I'll create into the 1.9 branch.

**Comment by Eldenroot** [comment]
@lairdshaw - I hope that 1.8 branch is not dead and will be maintained until mybb 1.9 RC will be out at least... I do not see any issue with these small patches and fixes... yeah, you can say - rebase is the issue, but there are plenty opened PRs with just few lines of code changed which are waiting for merge...

**Comment by lairdshaw** [comment]
>yeah, you can say - rebase is the issue, but there are plenty opened PRs with just few lines of code changed which are waiting for merge...

Yep, rebasing is exactly the issue. We've finally caught up (with the exception of a few later 1.8 branch merges) and we don't want to get back on the merry-go-round again, which could happen if we keep on merging 1.8 PRs. My view is that along with requiring new PRs to be submitted against the `dev-1.9` branch, we should only merge preexisting 1.8 PRs once we have a fully-functional 1.9 branch, so that folk *do* feel comfortable submitting PRs there rather than to the 1.8 branch.

**Comment by Eldenroot** [comment]
@lairdshaw - I understand but this is a small change and MyBB 1.8 will be there another XXX years... these PRs should be accepted in my opinion.

**Comment by lairdshaw** [comment]
> @lairdshaw - I understand but this is a small change and MyBB 1.8 will be there another XXX years... these PRs should be accepted in my opinion.

@Eldenroot - I'm in a bit of a slump at the moment so not really active in development. I hope though to get back into the saddle as soon as I can, and then I'll try to make an effort to regularly rebase new 1.8 PRs onto 1.9, so that (1) your (pretty reasonable, after all, in my view) expectations are met and at the same time (2) we don't end up with a massive backlog of PRs that need rebasing, delaying our progress. So, sure, I personally no longer have a problem with PRs like this being merged. I haven't discussed it with anybody else though.

**Comment by Starpaul20** [comment]
Given this only adds a hook to the Admin CP, I'd don't see any reason why this can't be merged.

**Comment by Eldenroot** [comment]
@dvz 1.8.33?

**Comment by Sama34** [comment]
I agree the addition is too minuscule as to have to wait, but if added it should be accompanied along the proper updates to documentation for it.
https://docs.mybb.com/1.8/development/plugins/hooks/

**Pull request closed without merging**
