### PR TITLE
changed raw values into constants #1736

### PR DESCRIPTION
**Pull request by JanMalte**

### CODE REVIEW

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/issues/1736

**Comment by JanMalte** [comment]
Changed manually to make sure only the right values are changed.

**Comment by PirataNervo** [comment]
That's quite a lot of work :P I went through many and didn't find any problems. Still, after reading so many my eyes are likely to miss any problems that may exist. We need more eyes here.

@mybb/developers @JN-Jones @Destroy666x @ATofighi

**Comment by PirataNervo** [comment]
@demonate

**Comment by Destroy666x** [comment]
@ATofighi, your script looks good, but just in case I'd also make the space between `,` and the number optional in case it was forgotten, for example `$mybb->get_input('something',1)` Same for possible space after `(int)`: `(int) $mybb->input['xxx']`

**Comment by ATofighi** [comment]
I'll merge it and make other changes.

**Pull request merged**
