### PR TITLE
Fixes #2314 Wrong PM update array code

### LINKED ISSUE #2314: Wrong PM update array code
https://github.com/mybb/mybb/blob/feature/inc/tasks/dailycleanup.php#L48 - UIDs are assigned as keys, while the loop https://github.com/mybb/mybb/blob/feature/inc/tasks/dailycleanup.php#L80 assumes they're values. Thus it always updates the PM count of the 1st user.

### PR DESCRIPTION
**Pull request by Stefan-ST**
Fixes #2314

### CODE REVIEW

**Comment by Cu8eR** [comment]
Looks good

**Comment by Destroy666x** [comment]
Well, I was about to push this together with some small `update_pm_counter()` corrections (the description + few things are outdated and unused in it). I understand that you take over someone's assignments that weren't touched for a long time because the person is inactive, but there's no reason to do it after 10 days when the person came back. Not a big deal here though, I'll create another issue for that.

**Comment by Stefan-ST** [comment]
Sorry, due to the large number of tickets being assigned but untouched for months I sometimes forget checking the assignments.

**Comment by Cu8eR** [comment]
Guys, there are many issues assigned to someone for a long time without any progress. I understand that it is a hobby and all of us have personal life, but it is better to fix it by soon by someone else than wait another XX days/months. It would be nice to fix all issues which are assigned, many of them are quite old

**Comment by Destroy666x** [comment]
@Cu8eR we know that. But while it's not problematic to fix something after X months, two people working on the same thing during X days is a time waste for one.

**Pull request merged**
