### PR TITLE
Remove `DB_MySQL` database driver in core

### LINKED ISSUE #4550: Remove `DB_MySQL` database driver
Remove the `mysql` (`DB_MySQL`) database driver, and handle connections using the `mysqli` (`DB_MySQLi`, new default) driver instead for old configurations.

Related: #3797

### PR DESCRIPTION
**Pull request by dvz**
Resolves #4550

### CODE REVIEW

**Comment by euantorano** [comment]
Missed the installer reference it seems: https://github.com/mybb/mybb/blob/dev-1.9/install/index.php#L93

**Comment by euantorano** [comment]
Did you forget about my comment RE the installer, or is it intentional to leave that?

**Comment by dvz** [comment]
I want to submit PRs to replace the installer code soon, but just pushed a fix in case it causes errors in the meantime (https://github.com/mybb/mybb/commit/9d3711039c2738d8d3d18108be09de575b2a4d0b).

**Comment by euantorano** [comment]
> I want to submit PRs to replace the installer code soon, but just pushed a fix in case it causes errors in the meantime (https://github.com/mybb/mybb/commit/9d3711039c2738d8d3d18108be09de575b2a4d0b).

Fair enough, sounds like a plan to me.

**Pull request merged**
