### PR TITLE
Feature #1797 Database optimization v2

### PR DESCRIPTION
**Pull request by PaulBender**
All Database optimization from #1797

PostgreSQL and SQLite don't support unsigned ints.

### CODE REVIEW

**Comment by Cu8eR** [comment]
It looks good to me

**Comment by JN-Jones** [comment]
@PaulBender Can you fix the merge conflicts? ;)

**Comment by PaulBender** [comment]
Fixed

**Comment by JN-Jones** [comment]
Tested:
- [ ] MySQL Update
- [ ] PgSQL Update
- [ ] SQLite Update
- [ ] MySQL Installation
- [ ] PgSQL Installation
- [ ] SQLite Installation

**Comment by JN-Jones** [comment]
I couldn't find any issues. Neither with upgrading/installing nor any logical errors. If nobody else mentions any issues till tomorrow I'll merge this. @euantorano @Destroy666x

**Comment by euantorano** [comment]
Looks good to me.

**Comment by JN-Jones** [comment]
I caused conflicts with one of my PRs @PaulBender. Can you fix them and merge it afterwards?

**Comment by PaulBender** [comment]
Fixed conflicts and merging now...

**Pull request merged**
