### PR TITLE
Fix #1913 Database export should ignore views

### LINKED ISSUE #1913: Database export should ignore views
It shouldn't be possible to select views when exporting the database within the ACP. At the moment MyBB tries views as tables which inflates (automatic) database backups.

MyBB doesn't use views therefor this is low priority. Nevertheless it's a common database feature.

### PR DESCRIPTION
**Pull request by willhartman**
This only affected MySQL and MySQLi.

SQLite implementation already specifies tables only.
PostgreSQL doesn't include the views in information_schema.tables anyway.

### CODE REVIEW

**Comment by willhartman** [comment]
#1913

**Comment by Destroy666x** [comment]
The MySQL solution seems to be ok (haven't tested yet though), but what about PgSQL/SQLite? Both support views AFAIK. The MyBB code seems to get only the `table` type already, am I correct?

**Comment by JN-Jones** [comment]
> SQLite implementation already specifies tables only.
> PostgreSQL doesn't include the views in information_schema.tables anyway.

**Comment by euantorano** [comment]
Looks good to me, thanks!

**Comment by Destroy666x** [comment]
Missed the reply:

> SQLite implementation already specifies tables only.
PostgreSQL doesn't include the views in information_schema.tables anyway.

You're right, didn't notice it earlier somehow, I think github showed a blank 1st comment for some reason.

Anyways, I can confirmt it works too.

**Pull request merged**
