### PR TITLE
Fix #3773 quoting post from other threads not working.

### LINKED ISSUE #3773: Quoting post from other threads not working
See [this community post](https://community.mybb.com/thread-224271.html) for detail. It's a JavaScript problem of using an invalid selector for the SCEditor instance, preventing quoting post(s) from other threads when replying or posting a new thread.

A quick fix is to use `MyBBEditor` that is defined [here](https://github.com/mybb/mybb/blob/f8066f4a4c92bfd0bf4b79567a7938206769c293/install/resources/mybb_theme.xml#L14000). However, the type check with only `undefined` seems not that enough.

### PR DESCRIPTION
**Pull request by yuliu**
A quick fix for #3773, detail goes [this thread](https://community.mybb.com/thread-224271.html).

### CODE REVIEW

**Comment by yuliu** [comment]
Didn't notice that posting new thread is having this issue, too. Wait for one more commit.

**Comment by yuliu** [comment]
Sorry, I've missed that. The version has been increased to 1822 for them and templates including them.

**Comment by euantorano** [comment]
Great, thanks!

**Comment by yuliu** [comment]
Seems not working on MyBB community forum. Will check later.

`Quote these posts now` from quick reply on showthread page now gives:

```
TypeError: MyBBEditor is null                        thread.js:138:4
    multiQuotedLoaded https://community.mybb.com/jscripts/thread.js?ver=1822:138
    complete https://community.mybb.com/jscripts/thread.js?ver=1822:106
```

**Pull request merged**
