### PR TITLE
Remove unnecessary name tag from announcement templates

### LINKED ISSUE #3967: Template Bug: modcp_announcements_edit input name attribute
The name attribute of the input element seems to be set unintentionally and needs an update.

Version: 1.8.21 / Original MyBB Theme.

Template (line 74):
modcp_announcements_edit

XML resource:
./install/resource/mybb_theme.xml (line 6474):

&lt;input type=&quot;submit&quot; class=&quot;button&quot; name=&quot;Edit Announcement&quot; value=&quot;{$lang-&gt;edit_announcement}&quot; /&gt;&amp;nbsp;&amp;nbsp;
[ExiTuS]

Edit: The same for modcp_announcements_new

Template (line 73):
modcp_announcements_new

XML resource:
./install/resource/mybb_theme.xml (line 6604):

&lt;input type=&quot;submit&quot; class=&quot;button&quot; name=&quot;Add Announcement&quot; value=&quot;{$lang-&gt;add_announcement}&quot; /&gt;&amp;nbsp;&amp;nbsp;
[ExiTuS]

Original thread: [Template Bug: modcp_announcements_edit input name attribute](https://community.mybb.com/thread-225459.html)

### PR DESCRIPTION
**Pull request by ryanstubbs**
Resolves #3967

### CODE REVIEW

**Comment by Ben-MyBB** [comment]
@Eldenroot any chance you can test this one?

**Comment by Eldenroot** [comment]
I am sorry, I am away right now. But it seems to be fine, he just changed hardcoded values into lang strings.Update template versions

**Comment by Ben-MyBB** [comment]
@euantorano Tested this and everything still works as expected with no undesired effects. Just require those template bumps before merging. Can always merge and then I can manually bump if easier.

**Comment by JordanMussi** [comment]
@Ben-MyBB if enabled you can push a commit to this PR

**Comment by Eldenroot** [comment]
I think that you can make changes to this PR.

BTW - applied to my board, tested briefly and no issue. It is just a small change.

**Comment by euantorano** [comment]
I can commit directly to this PR, I just tend to give authors a chance first as a learning experience and as a courtesy 😄

**Comment by ryanstubbs** [comment]
Hi, sorry, I'm new to pull requests in general so I apologise if this is wrong. I've updated those now. :)

**Pull request merged**
