### PR TITLE
Fixes #3378 - Add a check box "remember_me"

### LINKED ISSUE #3378: Check box "remember_me" missing from No Permissions Login
In the template 'error_nopermission', the checkbox "remember_me" is missing since v1.40 !!!

I did not look for the older versions ...
Maybe it's missing since the beginning of mybb?

To fix this, insert the following code :
Code:
`snipped`

after this row :
Code:
`snipped`

to obtain :
Code:
`snipped`

For next version please update /install/resources /mybb_theme.xml.

Thanks

Original Thread: [Check box "remember_me" missing](https://community.mybb.com/thread-219117.html)

### PR DESCRIPTION
**Pull request by Eldenroot**
#3378

### CODE REVIEW

**Comment by AndreRl** [comment]
Good job! I was wondering about the positioning of it. It looks a bit weird as is.

**Comment by Eldenroot** [comment]
OK, what do you suggest, no problem to change it.

**Comment by AndreRl** [comment]
Maybe aligned to the right? But when you look at the error no permission login and member login they’re actually really different. We should change them to be the same for consistency. @effone what do you think?

**Comment by Eldenroot** [comment]
I will check and try to find the beat way. Feel free to share your ideas :)

**Comment by euantorano** [comment]
In my opinion we can leave the layout as it is for now. The layout of these pages will change in 1.9 and if this looks the same as existing 1.8 pages it should be fine 😄

**Comment by justinsoltesz** [comment]
Center aligned matches the full login page, so it's good enough for now.

As you said, layout will change in 1.9.

**Comment by euantorano** [comment]
Awesome, thanks for the quick response Justin. I'll merge this now in that case!

**Pull request merged**
