### PR TITLE
Fix #2464 Add option to set cookies with Secure flag

### LINKED ISSUE #2464: Add option to set cookies with Secure flag
Server: https://github.com/mybb/mybb/blob/mybb_1807/inc/functions.php#L1810
Client: https://github.com/mybb/mybb/blob/mybb_1807/jscripts/general.js#L483

as suggested in https://community.mybb.com/thread-198899.html

### PR DESCRIPTION
**Pull request by Devilshakerz**
#2464

### CODE REVIEW

**Comment by JN-Jones** [comment]
This has conflicts @Devilshakerz Can you take a look so I can test it?

**Comment by Devilshakerz** [comment]
Rebased

**Comment by JN-Jones** [comment]
@Ben-Conway can you take a look at this?

**Comment by JN-Jones** [comment]
Can somebody take a second look? Seems fine to me but having a second opinion here would be good.

**Comment by euantorano** [comment]
Seems good to me too.

**Pull request merged**
