### PR TITLE
Fix #1321 Multipage doesn't work if portal.php is renamed

### LINKED ISSUE #1321: Multipage doesn't work if portal.php is renamed
We currently _support_ renaming `portal.php` to `index.php` but if administrators do so the pagination no longer works.

### PR DESCRIPTION
**Pull request by Sama34**
Fix #1321 Multipage doesn't work if portal.php is renamed

### CODE REVIEW

**Comment by Sama34** [comment]
That should fix it.

**Comment by Destroy666x** [comment]
Looks ok, but what about `THIS_SCRIPT`?

**Comment by Sama34** [comment]
`THIS_SCRIPT` is a constant and shouldn't change for backwards compatibility with plugins that do use it. Renaming the file will make no differences whatsoever over it really.

**Comment by Destroy666x** [comment]
Ah, you're right I guess.

**Pull request merged**
