### PR TITLE
Fixes #3014 - Signatures in PMs

### LINKED ISSUE #3014: send_pm() and signatures
Please remove the default signature = 0 for the send_pm() function.

It is a great function but by disallowing signatures here you can't have a useful signature for staff or site bots when providing warnings or other automated pms.

### PR DESCRIPTION
**Pull request by Eldenroot**
#3014

### CODE REVIEW

**Comment by Eldenroot** [comment]
@euantorano

**Comment by euantorano** [comment]
Sorry for the delay @Eldenroot. I'll try and check this this week for you.

**Comment by Eldenroot** [comment]
@Shade- @euantorano and others - is possible to merge this, I need to clean up my GitHub a little bit (many branches, patches an so on).

**Comment by euantorano** [comment]
I’m away from home this weekend, but I will look next week.

**Comment by Eldenroot** [comment]
@euantorano - please can you review this PR? Thank you!

**Pull request merged**
