### PR TITLE
Fixes #1982 - Missing $lang->error_invalidsearch

### LINKED ISSUE #1982: Missing $lang->error_invalidsearch
As it has been said on Slack, this is missing: https://github.com/mybb/mybb/blob/feature/misc.php#L257 in misc.lang.php

### PR DESCRIPTION
**Pull request by Cu8eR**
#1982 

This should fix this issue... for other missing lang strings it would be better to create a new issue (or update this PR)

### CODE REVIEW

**Comment by Cu8eR** [comment]
WIP, do not merge

**Comment by Cu8eR** [comment]
@Destroy666x - it should be done, I hope that I didnt miss any

**Comment by Destroy666x** [comment]
I'll check later but I'm quite sure some of them are not needed in `misc.php`, e.g. `error_invalidthread` and `error_invaliduser`

**Comment by Cu8eR** [comment]
Fixed! Thank you

**Comment by Cu8eR** [comment]
Updated for last changes

**Comment by euantorano** [comment]
Tested, looks fine to me.

**Pull request merged**
