### PR TITLE
allow users to access contact.php when board status is set to closed

### PR DESCRIPTION
**Pull request by kawaii**
This just seemed logical to me. Perhaps it could do with having a setting created but I don't see why this shouldn't just be allowed.

### CODE REVIEW

**Comment by kawaii** [comment]
Reasonable suggestions. :slightly_smiling_face: If I get the time I'll amend this PR, but I'm not a native PHP developer so it's probably best that someone else picks this up from inside the team.

**Comment by JordanMussi** [comment]
It's the same as what you've already done, just a few lines further down with the `$force_bypass` variable.

**Comment by Ben-MyBB** [comment]
@kawaii Any update on this?

**Comment by kawaii** [comment]
@Ben-MyBB I think this PR needs to be closed and I need to remake it with the suggested modifications since I deleted the original fork and can't figure out the correct git commands to extend this PR itself.

**Pull request closed without merging**
