### PR TITLE
Fixes #1243 Hide stuff users can't see v2

### LINKED ISSUE #1243: Hide stuff users can't see v2
- [ ] Buddy buttons in profiles (http://community.mybb.com/thread-157572-page-2.html)
- [x] hide Signature checkbox in Post Options in new reply/thread and editpost if user has no permission to have signature
- [x] show results template instead of vote template if user has no group/forum permission to vote in polls
- [ ] away peekers in UCP/MCP should depend on the current status
- [x] some UCP options should be hidden based on settings (for example quick reply if it's disabled globally)
- [x] Subscription link on showthread shows up for guests
- [x] The private messaging section of the User CP shows up even if your usergroup doesn't have permission to use the PM system
- [x] The Private Messages and Search bits in the header shows up regardless of settings/usergroup permission

@Destroy666x  did you created an issue for this? If so feel free to close, couldn't find it myself.

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #1243

Doesn't fix first and fourth item in the issue (not sure if they're worth fixing TBH).

### CODE REVIEW

**Comment by JN-Jones** [comment]
Couldn't find any obvious issues in the code, need to test it on my demo board though. @PaulBender could you look at the conflict?

**Comment by PaulBender** [comment]
Fixed

**Comment by PaulBender** [comment]
Fixed merge conflicts again

**Comment by Cu8eeeR** [comment]
Works fine for me, is there somebody else who can confirm?

**Comment by JN-Jones** [comment]
Apart from the conflicts this works as it should and can be merged. However I've noticed another related bug: If the user groups isn't allowed to access the UCP at all, all related links are still shown. Note that disabling the UCP doesn't disable the PM system so that part of the UCP doesn't even throw no permission errors. @PaulBender it's your descision whether you want to merge this after fixing the conflicts and creating a new PR or fixing that issue here too. The fixes so far have been confirmed to work.

**Comment by PaulBender** [comment]
Fixed merge conflicts and the User CP menu stuff.

**Comment by JN-Jones** [comment]
What with the UCI link on the left in our header? It was shown too and linked to the dashboars IIRC

**Comment by PaulBender** [comment]
Done.

**Comment by Ben-Conway** [comment]
Great work, looks good to me.

**Comment by Ben-Conway** [comment]
@JN-Jones Are you happy with this?

**Pull request merged**
