### PR TITLE
Fix #2522 - Links executing JS functions should return false and point to javascript.void(0) instead of hashtags

### LINKED ISSUE #2522: Links executing JS functions should return false and point to javascript.void(0) instead of hashtags
As discussed [here](https://community.mybb.com/thread-163831.html), links which trigger JS functions should point their href attribute to `javascript.void(0)` instead of a mere hashtag `#` and `return false` to normalize browser behavior.

### PR DESCRIPTION
**Pull request by Shade-**
#2522 

I've also standardized onclick calls (some are called with an old-fashioned javascript: prefix, the majority don't so I've deleted the javascript: prefix where present).

Despite fixing the issue, I do believe onclick should be avoided and added to inline scripts where possible.

### CODE REVIEW

**Comment by Destroy666x** [comment]
Template versions should be updated

**Comment by Shade-** [comment]
My bad, I will update the PR ASAP.

**Comment by JN-Jones** [comment]
I'm not sure whether eg radiobutton listeners needs the return false as we don't need/want to stop the default handling there (we only  want to do additional stuff). However I haven't checked how browsers even handle that. Will report back as soon as  I've done that.

**Comment by Shade-** [comment]
Darn, you're right. Returning false on checkboxes should prevent their usage in favor of the function executed, so they shouldn't return false at all. I'm going to update the PR.

**Comment by Shade-** [comment]
@Destroy666x how does template versioning works? In the latest commit I've just added +1 to the existing values, but I'm not sure it'll work.

**Comment by JN-Jones** [comment]
The values should represent the next version so `1809` for those you're going to change with this PR

**Comment by Shade-** [comment]
Done. Sorry for the multiple commits, I'm still familiarizing with command-line git.

**Comment by WildcardSearch** [comment]
This is a good thing, but I agree with Shade, I'd like to see event handling done dynamically.

**Comment by JN-Jones** [comment]
PR looks good to me. @mybb/sqa If noone else has any objections I'm fine with merging this later after testing a few more places

**Comment by JN-Jones** [comment]
Can't find anything wrong, if @mybb/sqa doesn't report anything wrong within the next few hours I'm merging this.

**Comment by JN-Jones** [comment]
Merging this then

**Pull request merged**
