### PR TITLE
Fixes #3886 - $_FILES['attachments'] check

### LINKED ISSUE #3886: Thread Modes $_FILES['attachment'] instead of $_FILES['attachments']
https://community.mybb.com/thread-226313-post-1342675.html#pid1342675

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #3886

### CODE REVIEW

**Comment by yuliu** [comment]
`($mybb->get_input('newattachment') || $mybb->get_input('updateattachment') || ($mybb->input['action'] == "do_editpost" && isset($mybb->input['submit']) && $_FILES['attachment']))` seems legacy code to me.

Just a guess: the script probably will never runs into this part `($mybb->input['action'] == "do_editpost" && isset($mybb->input['submit']) && $_FILES['attachment'])`.

And yes, input's `name` attribute `attachment` does have been changed to `attachments` in the `post_attachments_new` template.

**Comment by lairdshaw** [comment]
> Just a guess: the script probably will never run into this part `($mybb->input['action'] == "do_editpost" && isset($mybb->input['submit']) && $_FILES['attachment'])`.

The script runs into that part when the user selects one or more files with the "Choose Files" button and then clicks "Update Post" (but yes, only once $_FILES['attachment'] is corrected to $_FILES['attachments']).

**Comment by yuliu** [comment]
> > Just a guess: the script probably will never run into this part `($mybb->input['action'] == "do_editpost" && isset($mybb->input['submit']) && $_FILES['attachment'])`.
> 
> The script runs into that part when the user selects one or more files with the "Choose Files" button and then clicks "Update Post" (but yes, only once $_FILES['attachment'] is corrected to $_FILES['attachments']).

Oh yes, and with both changing `submit` => `submitbutton` and `attachment` => `attachments`. But now this "update post" action only confusingly results in uploading an attachment (default theme doesn't allow multiple attachments uploading at once) and returning to the edit screen, not the intended operation of updating a post.

**Comment by lairdshaw** [comment]
> But now this "update post" action only confusingly results in uploading an attachment

It works correctly for me. Clicking "Update Post" uploads the file(s) and returns to the post in thread view mode. Are you sure you have applied the full PR of #3926?

> default theme doesn't allow multiple attachments uploading at once

Uploading multiple attachments works fine for me (using the default theme on a vanilla MyBB installation with PR #3926 applied).

**Comment by Sama34** [comment]
I'm quite confused if this is a duplicate of #3926 or vice versa. If so, the proposal is to drop one of the PRs?

@Eldenroot do you have details about what this is supposed to fix? Stefan's post didn't provide much information.

**Comment by lairdshaw** [comment]
> I'm quite confused if this is a duplicate of #3926 or vice versa.

Vice versa, except that #3926 fixes additional bugs too.

> If so, the proposal is to drop one of the PRs?

Yes, the proposal is to drop this PR. #3926 builds on this PR, and if I were cluey enough with Git/GitHub (assuming it's even possible), I would have added the commits of #3926 on top of the commits of this PR, so that this one didn't have to be dropped - but I'm not (cluey enough).

> @Eldenroot do you have details about what this is supposed to fix? Stefan's post didn't provide much information.

I hope you don't mind me answering in @Eldenroot's absence, but my understanding of what this fixes is as I described it in that part of #3926 which applies to these typos:

> 1. When the "Post Thread" or "Post Reply" button was clicked after an attachment had been selected with the "Choose Files" button, the attachment was not saved.

**Comment by Eldenroot** [comment]
This PR can be closed, because it was replaced by this one #3926 (which contains this fix + few others) :) I am closing this one, if anything let me know :)

**Pull request closed without merging**
