### PR TITLE
Fixes #1674 Custom MyCodes not accepted by editor.

### LINKED ISSUE #1674: Custom MyCodes not accepted by editor.
> Create a new custom MyCode:
> Regular Expression:
> 
> ``` regex
> \[code=gist\](.*?)\[/code\]
> ```
> 
> Now try your new MyCode in a new thread/post. The code gets replaced by a common `[code]` MyCode.
> 
> Full or source editor doesn't makes the difference it seems.

Original thread: [Custom MyCodes not accepted by editor.](http://community.mybb.com/thread-163255.html)

### PR DESCRIPTION
**Pull request by martec**
Fixes #1674

### CODE REVIEW

**Comment by Cu8eR** [comment]
@martec

**Comment by martec** [comment]
@Cu8eR 

plz read https://github.com/mybb/mybb/issues/1674

**Comment by Sama34** [comment]
I think this is not to be fixed.

**Comment by ATofighi** [comment]
@Sama34 
IIRC it fixes the issue for `code` and `php` tags.

**Comment by Sama34** [comment]
But as you mentioned new issues come with the _fix_. I think the overall issue can't be really fixed and users should instead not create custom MyCodes like those.

**Comment by Destroy666x** [comment]
We could do it for every tag as the SCEditor developer said, but I don't think it's a good solution either.. So if noone has a better idea, I'm for not fixing this issue too.

**Comment by Destroy666x** [comment]
I still don't think that doing it for each tag is worth a hassle and noone had objections after my last reply, so closing. Still hoping SCE developers will come up with a better solution.

**Pull request closed without merging**
