### PR TITLE
Fixes #1926 Upgrades from <=1.2.14 fails

### LINKED ISSUE #1926: Upgrades from <=1.2.14 fail
In upgrade12.php rebuild_stats() is called which queries deletedthreads and deletedposts causing a MySQL error (unknown column).

### PR DESCRIPTION
**Pull request by Stefan-ST**
Fixes #1926

### CODE REVIEW

**Comment by Sama34** [comment]
That was an interesting one. I didn't test everything after the upgrade but there is an issue with the global.css style sheet right after upgrading:
mybb1214

The administrator needs to revert the style sheet for the default 1.8 theme to be correctly displayed (assuming the default 1.2.14 theme is being used as in my test environment).

I don't consider the need for that to be fixed considering administrators will probably use a new theme or something so I will merge this.

**Comment by Stefan-ST** [comment]
@Sama34 Upgrading from 1.6.x to 1.8.x doesn't reset the stylesheets either, does it?

**Comment by JN-Jones** [comment]
It only updates the master stylesheet, if you haven't modified it it should be updated otherwise not.

**Comment by Sama34** [comment]
I didn't edit `global.css` at all before upgrading so I would expect it should still be inhered from its parent after the upgrade. I had to revert it for the theme to work.

But there as always been issues like this in all upgrades IIRC anyways.

**Comment by ATofighi** [comment]
@Sama34 do you clean the cache of your browser?

**Comment by Sama34** [comment]
I'm pretty sure cache was not the issue, yes.

**Pull request merged**
