### PR TITLE
Fix #1453

### LINKED ISSUE #1453: Smilie breaks JS when ending with backslash
Hi all

After upgrading my forum to 1.8 I noticed that no js based stuff worked at all and I tracked it back to one of my smilies, which had the code ":-\" at the time. That code is inserted in the smilie function in js and escapes the closing quote =&gt; js syntax error.
I've changed to ":-/" for now so it works but the smilie codes should be checked before inserting them in js.

Bye.

Original thread: [Smilie breaks JS when ending with backslash](http://community.mybb.com/thread-159684.html)

### PR DESCRIPTION
**Pull request by Destroy666x**
Used addslashes() to prevent smilie JS errors (not sure if it's the best
solution, but it was used in misc.php only for some reason).

Also added spaces in misc.php inserter for consistency and listed the
replacements in new lines instead of separating them with space/comma
which looks kinda weird.

https://github.com/mybb/mybb/issues/1453

### CODE REVIEW

**Comment by PaulBender** [comment]
Looks good to me, just need to fix the merge conflicts.

**Comment by Sama34** [comment]
I tested this and also worked fine.

**Comment by ATofighi** [comment]
@Destroy666x

**Comment by PaulBender** [comment]
Merge conflicts still need fixing

**Comment by JN-Jones** [comment]
Merged manually, changed template version to `1804`.

**Pull request merged**
