### PR TITLE
Fixes #3781 - Long avatar URL causes MySQL error

### LINKED ISSUE #3781: Long avatar URL causes MySQL error
There should probably be better validation for this.

SQL Error:
1406 - Data too long for column 'avatar' at row 1
Query:
UPDATE mybb_users SET `avatar`='http:...', `avatardimensions`='62|62', `avatartype`='remote' WHERE uid='1'

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #3781

### CODE REVIEW

**Comment by Eldenroot** [comment]
Guys please review this :)

**Comment by Ben-MyBB** [comment]
@dvz can you give this a quick glance please?

**Comment by JordanMussi** [comment]
What about sqlite?
https://github.com/mybb/mybb/blob/b43cf6f7f6ec6aca745fc8ee469ea7ed0a6affa0/install/resources/sqlite_db_tables.php#L944

**Comment by dvz** [comment]
Best to check input length and show a message (or quietly set to empty), otherwise it can still result in errors.

**Comment by JordanMussi** [comment]
Also I can't see anything relating to ensuring the maximum length is 255 when updating in User CP:

https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/usercp.php#L2487-L2492

**Comment by JordanMussi** [comment]
Beaten to it by @dvz! It might be a good idea to refactor to use the user datahandler and put the validation in there 😃

**Comment by euantorano** [comment]
Yeah, if the data handler is used to update the handler, the validation should be done there. Most plugins affecting avatars would hopefully use the data handler so having the validation there makes sense.

**Comment by dvz** [comment]
We'll need upgrade code as well.

**Comment by Sama34** [comment]
I think is necessary to increase the field size, instead the user datahandler should validate user input.

**Pull request closed without merging**
