### PR TITLE
Fixes #3486 Missing Moderation Notices

### LINKED ISSUE #3486: Missing Moderation Notices
I remember previously stumbling across this issue myself but I do not know why I never actually pushed to get a solution for it. After reading [How To?] Notifications to moderators about unapproved posts I was once again reminded that MyBB does not give notice of all moderation notices.

As it stands all posts, threads and attachments that need moderator approval are not being notified with a moderation notice like you would get for reported content.

This solution from 2011 does work (I just tested it) however I am not sure how up to par the coding is and haven't actually looked at it hard enough. I'm also TERRIBLE at trying to maneuver or work GitHub so I figured I would post this here for someone else that may be able to actually do pull requests and changes and what not that are necessary.

I do believe this should have always been standard/core MyBB, after all if it is in the moderation queue it should be notified to all moderators or those with Mod CP access.

Original thread: [Missing Moderation Notices](https://community.mybb.com/thread-220422.html)

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #3486

### CODE REVIEW

**Comment by Eldenroot** [comment]
Great, testing since yesterday, seems to be fine. I had been using plugin for that. Thank you!

**Comment by effone** [comment]
Thanks for testing @Eldenroot, There is a very neat-pick issue I have observed with this PR but failed to find the root cause, is an additional space after each link.
snap
I have cross-checked templates, used `trim()` but no luck. That may be my cluttered experiment-exhausted code base. Can you confirm and / or try to find the root cause?

**Comment by Eldenroot** [comment]
I will try to reproduce in 5 hours, back in my office right now. Maybe sometjing similar with board stats (online members) in footer bug which was solved in 1.8.17 IIRC?

**Comment by effone** [comment]
Okay I have found the issue. Its the new line inserted by `template` class.
```

		if($htmlcomments)
		{
			if($mybb->settings['tplhtmlcomments'] == 1)
			{
				$template = "<!-- start: ".htmlspecialchars_uni($title)." -->\n{$template}\n<!-- end: ".htmlspecialchars_uni($title)." -->";
			}
			else
			{
				$template = "\n{$template}\n";
			}
		}
```
If I remove all `\n` from it issue gets resolved. I don't know how to handle this.
@euantorano ?

**Comment by effone** [comment]
Alright I have fixed it. There was a parameter `$htmlcomments` for `get()` method that required to be set to `false`. Love MyBB.

**Comment by euantorano** [comment]
Nice catch @effone!

**Pull request merged**
