### PR TITLE
Fixes #3995 Only parent forum's mod/modcp permissions are used in ModCP

### LINKED ISSUE #3995: Only parent forum's mod/modcp permissions are used in ModCP
It means that individual settings of mod/modcp permissions of the user or user group won't work for child forums in ModCP, if the child forums exist and child's permissions are different from the parent's.

### PR DESCRIPTION
**Pull request by yuliu**
Resolves #3995.

Test this PR:
1. Create forum A and its sub-forum B.
1. Assign a user U as moderator of forum A and B, explicitly. Make sure U or U's usergroup isn't any other forum's moderator.
1. Arbitrarily set different moderating permissions for the user U for forums A and B. For example, `canviewmodlog` is `yes` in forum A but `no` in forum B, `canmanageannouncements` is `no` in forum A but `yes` in forum B.
1. Go to ModCP's relevant sections to see if permissions are in effect.

### CODE REVIEW

**Comment by yuliu** [comment]
There are some unexpected results by this PR (not a full list):
- Display goes wrong in announcement management for forums in which current moderator doesn't have `canmanageannouncements` permissions.

And there are some remaining related issues not addressed for now (not a full list):
- Modlogs in ModCP shows nearly all records.

I'll try to keep this PR updated.

**Comment by yuliu** [comment]
@Sama34 Could you please review this PR? There are still lots of minor issues in ModCP, so I'd like to open new issues and PRs to address them separately.

**Comment by Eldenroot** [comment]
@yuliu - please open the new issues and send PRs. I have applied this fix to my board and I will report results ASAP.

**Comment by Ben-MyBB** [comment]
@Eldenroot any update on this one?

**Comment by Eldenroot** [comment]
I havent found any issue so far, but would be great to get feedback from others to be sure and check all possibilities.

**Pull request merged**
