### PR TITLE
Fixes #2020 Referrals Are Lost on Account Merge

### LINKED ISSUE #2020: Referrals Are Lost on Account Merge
As the title says.

If account A has 6 referrals and is merged into account B with only 1 referral then it will still only say they have 1 referral.

It should carry over IMHO, same with reputation actually.

Original thread: [Referrals Are Lost on Account Merge](http://community.mybb.com/thread-167259.html)

### PR DESCRIPTION
**Pull request by effone**
Attempt to fix #2020 
- Referrer / Referrals carry over
- Undefined / Same user error logic fine tuning
- Slight code optimization

Note: Addressing only the titled issue for now. If the extended part as mentioned in comments (related to reputation, not referrals) are also required that can be done too ...

### CODE REVIEW

**Comment by Eldenroot** [comment]
@effone - for others mentioned issues - will you add them into this PR later or a new PR in future? Thank you, I will test this soon.

**Comment by effone** [comment]
I kept the decision open as to target the issues in an optimized way. As @euantorano directed big / complicated modifications are part of 1.9 as many of those may get resolved during coding itself. If it is required I have no issue adding the fix to this PR.

**Comment by Eldenroot** [comment]
Maybe would be nice to get things sorted properly... if it is not a big change, I vote to add it to this PR (or the new one). @euantorano

**Comment by euantorano** [comment]
I would class these as bugs rather than new features, and bug fixes can still be done in 1.8.x.

The stuff that I really want to leave until 1.9 is anything that has lots of template changes, as that makes merging 1.8 and 1.9 extremely difficult.

**Comment by Eldenroot** [comment]
Can someone create a new ticket for that? I agree that this is a bug rather that a new feature.

**Pull request merged**
