### PR TITLE
Fix #1673 wrong online location links

### LINKED ISSUE #1673: View online list shows buddy list popup link
>When viewing the online list it shows "Viewing Buddy List".
I don't think this is intended as you see the raw content that's meant to be shown in a popup window: 

Original thread: [View online list shows buddy list popup link](http://community.mybb.com/thread-163647.html)

### PR DESCRIPTION
**Pull request by Destroy666x**
Fixes 2 and removes 1 outdated online location links.

https://github.com/mybb/mybb/issues/1673

### CODE REVIEW

**Comment by Cu8eR** [comment]
Looks good to me!

**Comment by Destroy666x** [comment]
Since these are very simple changes, they could be merged into 1.8.4 if someone has time to check them.

**Comment by Cu8eR** [comment]
@Destroy666x - I have checked this PR, everything should be OK. Anybody else who can confirm?

**Comment by Sama34** [comment]
Didn'tested but seems correct to me.

**Pull request merged**
