### PR TITLE
#2972 (stats.php) forum statistics to twig

### PR DESCRIPTION
**Pull request by Matslom**
For #2972 

- [x]  stats
- [x]  stats_thread
- [x]  stats_topforum

```diff
+ stats -> stats/stats.twig
- stats_thread
- stats_topforum
```

### CODE REVIEW

**Comment by Matslom** [comment]
Not sure about this lines. It's not very messy, but maybe splitting this lang into two parts would be better idea. 
https://github.com/Matslom/mybb/blob/fabee05ad8ff33ac807066949b94b1f73b23d4e1/inc/views/base/stats/stats.twig#L41-L42

**Comment by euantorano** [comment]
@Matslom It may make sense to split that language variable into two parts, yeah. It doesn't look too bad like this though, so I'd be happy to merge this if you're happy with it.

**Comment by Matslom** [comment]
@euantorano So I will split it to two parts. Tomorrow most likely.

**Comment by euantorano** [comment]
Great, thank you very much.

**Comment by Matslom** [comment]
@euantorano I will try fix it in this week.

**Comment by skmedix** [comment]
@euantorano You can close it now.

**Pull request closed without merging**
