### PR TITLE
#4026 Attachments aren't parsed in print preview

### LINKED ISSUE #4026: Attachments aren't parsed in print preview
Apparently attachments aren't parsed in print preview (printpreview.php) whereas the post parser works fine.

I don't think this is expected behavior.

Original thread: [Attachments aren't parsed in print preview](https://community.mybb.com/thread-227269.html)

### PR DESCRIPTION
**Pull request by rajat315315**
Resolves #4026

### CODE REVIEW

**Comment by Sama34** [comment]
I think it would be better if you build the attachment cache outside the while loop.

**Comment by euantorano** [comment]
I agree, we should build the cache for all of the posts at once with one query rather than 1 query per post.

**Comment by Eldenroot** [comment]
@rajat315315 - please can you complete this PR? Thx!

**Comment by Ben-MyBB** [comment]
@rajat315315 Would you be able to update this PR please?

**Comment by rajat315315** [comment]
Sorry guys, it's been really long time I opened MyBB source code. I would really have to start a fresh when looking at this PR.
Can anybody else take up this responsibility?

**Comment by euantorano** [comment]
No problem, I’ll make some changes to it tonight or tomorrow.

**Review by Sama34 — APPROVED** [review]

**Pull request merged**
