### PR TITLE
Resolve #3927 Add cache busting for CSS

### LINKED ISSUE #3927: Add cache busting for CSS
After editing a theme stylesheet, the changes are not showing in browser due to caching.

There are some forum-topics related to this issue:
- [[Rejected] Theme Caches When Changing CSS Around](https://community.mybb.com/thread-161108.html)
- [Preventing CSS Files From Getting Cached](https://community.mybb.com/thread-120243.html)
- [ [Performance] Forum not updating when I edit CSS](https://community.mybb.com/thread-180988.html)
- [Theme CSS Cache Query String Hashes to bust caches](https://community.mybb.com/thread-214223.html)
- [Add force cache refresh](https://community.mybb.com/thread-137537.html)
- [Global.css Changes Aren't Showing Up?](https://community.mybb.com/thread-100336.html)
- [CSS not updating](https://community.mybb.com/thread-102994.html)

...ect.

### PR DESCRIPTION
**Pull request by ievgent**
Resolves #3927

### CODE REVIEW

**Comment by euantorano** [comment]
It looks like this will only work when the cache file is used, correct? Obviously that works, but I'm not sure if we also want to support cache busting for `css.php` URLs. Thoughts @mybb/developers?

**Comment by Sama34** [comment]
Ideally it should be done in `css.php` as well. I would say to leave this for 1.9 but if somebody is willing to do it for 1.8 then I see no reason not to add it.

**Comment by ievgent** [comment]
> Ideally it should be done in `css.php` as well. I would say to leave this for 1.9 but if somebody is willing to do it for 1.8 then I see no reason not to add it.

Ok, I'll take a look at it.

**Comment by Eldenroot** [comment]
@ievgent - please can you update and finish this PR? Thx!

**Comment by Eldenroot** [comment]
@ievgent - Hi, please could you finish this PR? Thx!

**Pull request merged**
