### PR TITLE
Fixes #3960 - COPPA URL

### LINKED ISSUE #3960: COPPA URL is not valid anymore
As title says... it needs to be replaced (ACP and frontend part).

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #3960

### CODE REVIEW

**Comment by Eldenroot** [comment]
I used Wikipedia, it seems to be the best, I cannot find any official COPPA site anymore,

**Comment by Ben-MyBB** [comment]
Seems like the best solution. I couldn't find another COPPA website either.

**Comment by Sama34** [comment]
Isn't COPPA an USA law?
https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule
https://www.ftc.gov/tips-advice/business-center/guidance/complying-coppa-frequently-asked-questions

I think we should link to official government sites if available and applicable (COPPA, GDPR, and that stuff).

**Comment by Eldenroot** [comment]
No problem to change to FTC, but I need a feedback.

**Comment by Ben-MyBB** [comment]
@euantorano thoughts here? Seems mixed feelings between the link suggested and the FTC links. I would personally lean towards the FTC links since they're available.

**Comment by euantorano** [comment]
Yes, I would lean towards the official links preferably.

**Comment by Ben-MyBB** [comment]
@Eldenroot Please can you update the PR? Then I can get this one merged.

**Comment by Eldenroot** [comment]
OK, just a minute .)

**Comment by Eldenroot** [comment]
@Ben-MyBB #3962

**Pull request closed without merging**
