### PR TITLE
Fixes #2456 Hash instead of the password at the "forgot my password"

### LINKED ISSUE #2456: Hash instead of the password at the "forgot my password"
Hash instead of the password at the "forgot my password". I did not change in any way member.php file in the email displays the password hash added to the database instead of the decrypted password to login.

zrzut ekranu z 2016-08-06 10-17-30

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2456

### CODE REVIEW

**Comment by Sama34** [comment]
I think this reverts the purpose of the while loop. @Destroy666x

**Comment by Ben-Conway** [comment]
@JN-Jones said he tested it and it works okay.

**Comment by Destroy666x** [comment]
Yeah, it needs to be in the loop, otherwise it may fail because of a datahandler error.

**Comment by PaulBender** [comment]
Okay, I've moved it.

**Comment by Sama34** [comment]
Somebody mentioned the issue being the following line:
https://github.com/mybb/mybb/blob/feature/member.php#L1641

But I checked and apart from the misleading variable name it should work, yeah.

**Pull request merged**
