### PR TITLE
Fixes #3869 - Replace "sex" with "gender" 

### LINKED ISSUE #3869: Replace "sex" with "gender"

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #3869

### CODE REVIEW

**Comment by euantorano** [comment]
`sqlite_db_inserts` also needs updating.

**Comment by Eldenroot** [comment]
Following discussion here: https://github.com/mybb/mybb/pull/3788

I am not sure what is the final decision.

**Comment by Sama34** [comment]
I suggest:
- Dropping updating existing installs, only apply change for new installs.
- Drop this field altogether in future versions (1.9)

**Comment by euantorano** [comment]
Ok, that’s fine by me. Either way, the SQLite dB inserts need changing too. We can always put a notice in the release notes telling people they can change it themselves.

**Comment by Eldenroot** [comment]
I think this PR can be closed in favour of this one (original one) - https://github.com/mybb/mybb/pull/3788 am I right?

**Pull request closed without merging**
