### PR TITLE
Fixes PHP 8 compatibility issues.

### PR DESCRIPTION
**Pull request by yuliu**
1. The issue for tracking: #4593.
1. The message of each commit explains what it fixes (the PHP 8 compatibility issue).
1. The PR includes fixes for issues reported in #4602.
1. The PR includes fixes for some issues reported in https://github.com/mybb/mybb/issues/4530#issuecomment-1089224347 . This one may be closed when the PR is merged, since other issues reported in it can't be reproduced.
1. The PR doesn't fix all remaining PHP 8 compatibility issues. That means there are still more.
1. Some more commits will be pushed later, before marking the PR as ready.

### CODE REVIEW

**Comment by yuliu** [comment]
In commit https://github.com/mybb/mybb/pull/4613/commits/6b2fa22764219045a831bf2faaf7ac78bac9a878

 - Move post(s):
    - Undefined variable `$return_url` in eval()'d code (L27) in `moderation.php` (L2669).

Note: not sure if the variable `$return_url` used in template `moderation_inline_moveposts` is truly needed.

**Comment by yuliu** [comment]
Remarks in commit https://github.com/mybb/mybb/pull/4613/commits/64e8476a8ecee61ecc053f342252746106e686f9

 - `$pm['saveasdraft']` and `$pm['options']['XXX']` are added following how a pm is prepared in [`send_pm()`](https://github.com/mybb/mybb/blob/c3c474a5b70f9fb4bb368b5b58c623b1c9e2fc16/inc/functions.php#L8974):
https://github.com/mybb/mybb/blob/c3c474a5b70f9fb4bb368b5b58c623b1c9e2fc16/inc/functions.php#L9079-L9085
 - `$pm['saveasdraft'] = 0` is optional because the default for this option is `0`.
 - `$pm['options']['signature']` is set to `0`, given that the pms are to inform moderators/admins of a report.

**Comment by Eldenroot** [comment]
Will be merged into 1.8.33?

**Comment by yuliu** [comment]
Remarks for commit https://github.com/mybb/mybb/pull/4613/commits/128f8ea6e7c9cb8b3dc8a8975076714d995465d9

 - This is only a workaround for eliminating PHP warnings caused by the real issue reported in #4630.

**Comment by yuliu** [comment]
Remarks for commit https://github.com/mybb/mybb/pull/4613/commits/b153eb7861c904c94ea4a992215216b1fab15599

 - The fixed typo here (`canonlyviewownthread` -> `canonlyviewownthreads`) doesn't fully resolve the PHP warning issue:
   ```
   Warning [2] Undefined array key "canonlyviewownthreads" - Line: 1228 - File: inc\datahandlers\post.php PHP 8.1.13
   ```

 - The real issue behind this typo fix is about getting forum permissions:
    - `forum_permissions()` which calls
    - `fetch_forum_permissions()` that may return a set of group permissions where relevant permissions are missing --- those only exist in forum permissions (stored in `mybb_forumpermissions`) but not usergroup permissions (in `mybb_usergroups`), e.g., `canonlyviewownthreads`, `canonlyreplyownthreads`, etc.

**Comment by yuliu** [comment]
Since the code base is already in v1.8.33, while the PR is based on v1.8.32, it'll cost much more time to pinpoint recent reported issues.

More PHP 8 compatibility issues will be addressed in other PRs, and this one is marked as ready for review.

**Comment by yuliu** [comment]
More issues relating to the video mycode parsing have been reported in https://community.mybb.com/thread-237617.html . I'll push some commits that'll cover these issues later, to this PR.

**Comment by kgraefe** [comment]
Not sure if that's the right place, but I found some more in the admin panel of MyBB 1.8.33 that are not yet fixed, as far as I can tell from scanning through the PR:
mybb

This only happens when a view is selected that does not match any user.

Edit: You probably guessed it, but FTR: the error happens on PHP 8.0, 8.1 and 8.2. It does not occur on PHP 7.4.

**Comment by yuliu** [comment]
Remarks for commit https://github.com/mybb/mybb/pull/4613/commits/d0af36303c83730f5e51830d76fd4ef9cbf444ce

 - The commit should have fixed all issues related to the parser reported in https://community.mybb.com/thread-237617.html .
 - The following line was removed as the variable `$title` isn't used in the `video_metacafe_embed` template or anywhere else in the parser class. The removal may affect plugins that rely on the variable.

    https://github.com/mybb/mybb/blob/c3c474a5b70f9fb4bb368b5b58c623b1c9e2fc16/inc/class_parser.php#L1531

 - Currently, the parser can't correctly deal with URLs with any number of continuous `/` in its `path` part. [[REF]](https://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything)

**Pull request merged**
