### PR TITLE
Base Database Class

### PR DESCRIPTION
**Pull request by euantorano**
http://community.mybb.com/thread-162474.html

This pull request adds a base database class based on the MySQL classes but that works with MySQL, PgSQL and SQLite.

Also fixes potential error in db_pdo where it was using an undeclared variable $user when connecting.

### CODE REVIEW

**Comment by PirataNervo** [comment]
@euantorano you forgot to load the DB_Base interface in the core.

**Comment by euantorano** [comment]
Damn. Forgot we don't have such a thing as an autoloader :(

**Comment by PirataNervo** [comment]
I'm creating a new PR now

**Comment by PirataNervo** [comment]
https://github.com/mybb/mybb/issues/1652

**Comment by Sama34** [comment]
Was concerning such thing :P

**Pull request merged**
