### PR TITLE
Editor codeblock whitespace correction

### LINKED ISSUE #3975: Long text in [code] & [php] out of box bound in SCEditor
Is it possible to fix this? Seems it's because of the SCeditor's style, so will also affect 1.9.

Quote &amp; normal text looks great.

Original thread: [Long text in [code] & [php] out of box bound in SCEditor](https://community.mybb.com/thread-227600.html)

### PR DESCRIPTION
**Pull request by effone**
Signed-off-by: effone <me@eff.one>

Resolves #3975

### CODE REVIEW

**Comment by Eldenroot** [comment]
We have to make sure that these changes won't be overwritten during updating to a newer version of SCEditor in future. (and I hope that we will not use SCeditor anymore in MyBB 1.9).

**Comment by Ben-MyBB** [comment]
In my opinion, I honestly think the prospect of SCEditor being updated in 1.8 life-span is unlikely unless any major bugs or security issues appear.

**Comment by effone** [comment]
These CSS style files are not directly part of core SCE.

**Review by euantorano — COMMENTED** [review]
This looks good, and these theme files are fine to be altered (we alter them any time we upgrade SCEditor anyway). I'm just going to quickly test before merging.

**Comment by Eldenroot** [comment]
Works fine, tested.

**Pull request merged**
