### PR TITLE
Fix #1609 forum deletion

### LINKED ISSUE #1609: Incomplete forum deletion
Continuation of https://github.com/mybb/mybb/pull/1605

If you delete a forum, the following things are incorrect:
- [x] all threads and posts are deleted, but records associated with them such as forumsread/threadratings/threadsubscriptions/reportedcontent/polls/polloptions/attachments/etc. are left as orphaned litter in the database. Not good if you delete a forum with many threads. Deleting users works much much better: https://github.com/mybb/mybb/blob/feature/inc/datahandlers/user.php#L1426
- [x] global threads/posts stats are recounted, but stats for the parent forum(s) and for users that posted in the deleted forum (if the forum settings don't disable user post/thread counting) aren't recounted
- [x] `get_forum()` cache read is used to get the name of the deleted forum, but that doesn't make any sense since it can be selected in the forums table query 2 lines below too

### PR DESCRIPTION
**Pull request by JN-Jones**
#1609 (old PR: #1920)

Fixed the smaller issues mentioned in the previous PR. Only pagination is still missing. @Destroy666x

### CODE REVIEW

**Comment by JN-Jones** [comment]
Added pagination. It always deletes 50 threads, if there are still threads to delete redirects back to the same page, otherwise deletes other stuff. @mybb/sqa

**Comment by JN-Jones** [comment]
@Ben-Conway can you take a look at this?

**Comment by JN-Jones** [comment]
Can somebody please check this?

**Comment by Ben-Conway** [comment]
This looks good to me.

**Comment by Cu8eeeR** [comment]
My php knowledge is not great as your guys but I didnt find anything wrong on the first look. Still should be reviewed by someone more skilled than me.

**Comment by euantorano** [comment]
Looks good to me too 👍

**Pull request merged**
