### PR TITLE
Working on #2972 Template Conversion to Twig Format (nav)

### PR DESCRIPTION
**Pull request by Shade-**
For #2972. Templates converted:
- [x] nav
- [x] nav_bit
- [x] nav_bit_active
- [x] nav_dropdown
- [x] nav_sep
- [x] nav_sep_active

These were missing.

### CODE REVIEW

**Comment by Shade-** [comment]
Yeah sure I can fix that asap.

**Comment by euantorano** [comment]
Great, thanks!

**Comment by Shade-** [comment]
Thing is, we still need to add the breadcrumb in the end of processing, given bits are dynamically added by each file. I don't know yet how to handle Twig extensions, and I don't know what'd be the best approach here

**Comment by euantorano** [comment]
Hm, I’ll have a look at it and see if I can come up with something. If it’s done as an extension then the extension function will only be called when the layout file is rendered, which should be within `output_page` so we should be fine.

**Comment by euantorano** [comment]
This was superseded by #3404, so I'm closing this.

**Pull request closed without merging**
