### PR TITLE
Add Licence file

### PR DESCRIPTION
**Pull request by LostArchives**
Hello,
Thanks for your project. As I mentionned in the issue #2514 , I thought that adding the licence file to your project would be a good idea. I hope this contribution will help you :)

#2514

### CODE REVIEW

**Comment by Ben-Conway** [comment]
What's the verdict with this then? @Stefan-ST

**Comment by JN-Jones** [comment]
@Stefan-ST

**Comment by Stefan-ST** [comment]
@Ben-Conway @JN-Jones This PR is invalid because MyBB uses LGPL and not GPL as license. Not sure why you need me to notice this...

**Comment by JN-Jones** [comment]
The question here was first whether we need the license at all as there's also an issue about this...

**Comment by Stefan-ST** [comment]
@JN-Jones I've already commented on this question on Slack: "If it provides any advantage over the existing link in the readme file I'm fine with adding a license file"

**Comment by Destroy666x** [comment]
I don't see any reason to not add a proper licence file.

**Pull request closed without merging**
