### PR TITLE
Redirect_profileupdate - small change

### PR DESCRIPTION
**Pull request by Cu8eR**
for more info: http://community.mybb.com/thread-161147.html

### CODE REVIEW

**Comment by Destroy666x** [comment]
The capitalization should be corrected, for example:

> You will be now returned to the Username settings.

There is no reason to capitalize only the `Username` part.

**Comment by Cu8eR** [comment]
@so, no capital letters? Or chenge it to "Username Settings"?

**Comment by Destroy666x** [comment]
Either no capital letters or the exact name of the page, for example `Change Username page` (as in the menu).

**Comment by Cu8eR** [comment]
Updated

**Comment by Destroy666x** [comment]
It's ok.

Anyways, some more things:
- few phrases have `Thank you,` at the beginning and the rest not, I'd remove it from all phrases for consistency
- Edit Options redirect string is wrong, it says you're redirected to the subscription list
- https://github.com/Cu8eR/mybb/blob/patch-2/inc/languages/english/usercp.lang.php#L367 could be changed too, it redirects to the subscription list

**Comment by Cu8eR** [comment]
About the second point - you mean L327?

**Comment by Destroy666x** [comment]
Yep.

**Comment by Cu8eR** [comment]
@Destroy666x - should be OK now

**Pull request merged**
