### PR TITLE
Bump template version to 1817 for merged PRs

### PR DESCRIPTION
**Pull request by Eldenroot**
Bump template version to 1817 for already merged PRs - #3302 (issue #3308) and #3301 (issue #3311)

### CODE REVIEW

**Comment by effone** [comment]
DO we need this? Its against the rectifications made in 1.8.16 so, the template should carry that version only.

**Comment by euantorano** [comment]
For people who have already upgraded to 1.8.16, I think so yes. Not sure though.

**Comment by Eldenroot** [comment]
Unfortunately there are a lot of users who already updated to MyBB v1.8.16 :(

**Comment by effone** [comment]
Alright. Skipping this from assigning any milestone considering it an extension

**Comment by dvz** [comment]
https://github.com/mybb/mybb/blob/mybb_1816/admin/inc/functions_themes.php#L147
https://github.com/mybb/mybb/blob/mybb_1816/admin/modules/style/templates.php#L1280

The upgrade script seems to be updating all master templates and the ACP to be checking for any version difference so it might be fine to go with `1816` (verification needed).

**Comment by euantorano** [comment]
@dvz I think we're better safe than sorry and apply `1817` anyway, meaning we should merge this as is. Thoughts?

**Pull request merged**
