### PR TITLE
Fixes #2385 - missing lang string

### LINKED ISSUE #2385: ACP language and button function error
Here you see a deficiency.
user_banning.lang.php:  &#36; l [ 'search_user'] = 'User Search';

There admin/modules/user/banning.php code in the search button.
&#36; Buttons [] = &#36; form-&gt; generate_submit_butto's (&#36; lang-&gt; search_user, array ('name' =&gt; 'search'));
There's something wrong button, search entered user bans.

Original thread: [ACP language and button function error](http://community.mybb.com/thread-190249.html)

### PR DESCRIPTION
**Pull request by Cu8eR**
#2385

### CODE REVIEW

**Comment by ATofighi** [comment]
It's better to use `$lang->search_for_a_user$ variable. https://github.com/mybb/mybb/blob/feature/inc/languages/english/admin/global.lang.php#L359

**Comment by Destroy666x** [comment]
Right, and the other one could be removed completely

**Comment by Cu8eR** [comment]
I will review it, thx

**Comment by Cu8eR** [comment]
@Destroy666x @ATofighi @dequeues - should be fixed now

**Comment by euantorano** [comment]
Yep, looks good.

**Pull request merged**
