### PR TITLE
Fixes #2085 UserDataHandler::clear_profile

### LINKED ISSUE #2085: UserDataHandler::clear_profile
https://github.com/mybb/mybb/issues/1820#issuecomment-115888589

`UserDataHandler::clear_profile` should remove the user avatar. This method is used by the Purge Spammer feature.

### PR DESCRIPTION
**Pull request by Stefan-ST**
Fixes #2085

### CODE REVIEW

**Comment by Stefan-ST** [comment]
This is certainly not the most efficient way but remove_avatars() ensures consistent behaviour.

**Comment by Destroy666x** [comment]
This solution isindeed the best, but since when is `delete_uids` an array?

**Comment by Stefan-ST** [comment]
Whoops, thanks...

**Comment by Destroy666x** [comment]
Should be ok now. Haven't noticed any big optimization loss.

**Pull request merged**
