### PR TITLE
Visual fix in postbit_gotopost - CSS

### PR DESCRIPTION
**Pull request by Cu8eR**
Delete underline which is useless. CSS si used.

@Sama34

### CODE REVIEW

**Comment by Destroy666x** [comment]
The HTML from your previous PR wasn't invalid (empty `<a>` tags are allowed, only `href` is required), but this seems to be the best solution: http://stackoverflow.com/questions/10504544/is-it-ok-to-have-an-empty-anchor-tag?answertab=votes#tab-top

**Comment by Cu8eR** [comment]
I think that css solution is better than just delete space. Anyway both
solutions work fine. I prefer css

**Comment by Destroy666x** [comment]
> I think that css solution is better than just delete space

You're missing the "because" part here. I don't see why adding an additional line to a file that needs to be downloaded by the visitor if it's not cached would be better than removing a redundant HTML code.

**Comment by JN-Jones** [comment]
As both is valid I'd also prefer the HTML solution.

**Comment by Cu8eR** [comment]
Ok, so I will make a new PR with html solution. :)

**Comment by Cu8eR** [comment]
@Destroy666x @JN-Jones @Sama34  - I have made a new PR with HTML solution...

**Pull request closed without merging**
