### PR TITLE
Fix #4238 Add commit hook to attachments forum module (ACP)

### LINKED ISSUE #4238: Add commit hook to attachments forum module (ACP)

### PR DESCRIPTION
**Pull request by Sama34**
Fix #4238 Add commit hook to attachments forum module (ACP)

### CODE REVIEW

**Comment by Ben-MyBB** [comment]
Note: We would need to add this onto the hooks page https://docs.mybb.com/1.8/development/plugins/hooks/

**Comment by euantorano** [comment]
The hooks page is automatically generated, so it should just be a case of regenerating it.

**Comment by Sama34** [comment]
I think I will add more hooks to this module, just spare me a couple of days for reviewing so.

**Comment by awslabspl** [comment]
@euantorano If the page is automatically generated than there should be no need to trigger regeneration as new version will trigger regeneration automatically, am I right?

**Comment by Sama34** [comment]
It is currently complicate to tweak the filter options. There are other places where hooks could be useful which I will add.

**Comment by euantorano** [comment]
> @euantorano If the page is automatically generated than there should be no need to trigger regeneration manually as new version will trigger regeneration automatically, am I right?

I believe that part of our release workflow is to regenerate the page, but I don’t think it gets triggered automatically.

**Comment by euantorano** [comment]
I’m going to merge this as is for now, and we can open more PRs for any other hooks.

**Pull request merged**
