### PR TITLE
Fixes #2590

### LINKED ISSUE #2590: Who Posted Sorting Links Redirect To New Page
In forumdisplay.php when viewing the thread list and clicking the reply count link for the AJAX Who Posted modal...

...when clicking either sort link, the user is redirected to a page, empty except for the modal content:

Apologies if this is a duplicate, but I did search.

Original thread: [Who Posted Sorting Links Redirect To New Page](https://community.mybb.com/thread-206871.html)

### PR DESCRIPTION
**Pull request by WildcardSearch**
...where in the Who Posted modal dialog, sorting links redirected to a
new blank page. #2590

### CODE REVIEW

**Comment by euantorano** [comment]
Personally I'd rather we fixed the main misc page, but that would be a much bigger patch which wouldn't get into 1.8.10.

The current patch wouldn't work for users with JS disabled.

**Comment by WildcardSearch** [comment]
> Personally I'd rather we fixed the main misc page, but that would be a much bigger patch which wouldn't get into 1.8.10.

Yes, I thought of that, but the issue is based on a problem with the modal so I just stuck to handling the JavaScript issue. We can create a separate issue for the bigger problems.

**Comment by euantorano** [comment]
Sounds fair to me, can you please create the new issue?

**Comment by WildcardSearch** [comment]
Done.

**Pull request merged**
