### PR TITLE
fixed #2113

### LINKED ISSUE #2113: Attachment buttons doubled lined
I find this kind of annoying. The buttons should be displayed on one single line.

Original thread: [Attachment buttons doubled lined](http://community.mybb.com/thread-167619.html)

### PR DESCRIPTION
**Pull request by SvePu**
unbenannt

### CODE REVIEW

**Comment by Destroy666x** [comment]
This fix doesn't work on lower resolutions.

**Comment by SvePu** [comment]
What you mean? - The default mybb theme has a min-width defination.

**Comment by SvePu** [comment]
I earlier have tested it in Opera and now in FF - In Opera it has worked but FF it doesnt work

The max. witdh for this fix must be 60%

Please delete this PR - I'll make a new one.

**Comment by Destroy666x** [comment]
The best solution is `white-space: nowrap;` as I mentioned in the thread - it will ensure it doesn't break in all browsers under all resolutions.

**Pull request closed without merging**
