### PR TITLE
Fixes #2299 - Missing setting descriptions

### LINKED ISSUE #2299: Missing setting descriptions
Some settings, for example Custom User Title Maximum Length and Length limit in Signatures, don't explain what happens if the value is 0. It causes misunderstandings like this: http://community.mybb.com/thread-187524.html where users may expect different behavior - e.g. max length equal 0 in this case, which would basically mean disabling usertitles/signatures.

"0 to disable the limitation.", "0 for unlimited length." or anything similar could be added to their decription.

### PR DESCRIPTION
**Pull request by Cu8eR**
Fixes #2299 - Missing setting descriptions

### CODE REVIEW

**Comment by Destroy666x** [comment]
These 2 were just examples. There are at least fe more, e.g. Maximum Username Length, Maximum Attachments Per Post, etc.

**Comment by Cu8eR** [comment]
@Destroy666x - OK, I will add them soon. Thx

**Comment by Cu8eR** [comment]
I am not sure about these:

- Reputation Comments Per Page - 0 for no limit?
- Cut-off Time (mins)
- Maximum Page Links in Pagination - 0 for no limit?
- Members Per Page - 0 for no limit?
- Threads Per Page - 0 for no limit?
- Minimum Username Length - 0 for no limit?
- Maximum Username Length - 0 for no limit?
- Minimum Password Length - 0 for no limit?
- Maximum Password Length - 0 for not limit?
- Replies For Hot Topic
- Views For Hot Topic
- Maximum Attachments Per Post - 0 for no limit?

**Comment by Destroy666x** [comment]
You can check that in the core files, but most of them should be disabled with 0.

**Comment by Cu8eR** [comment]
@Destroy666x - I will change it as soon as the WIP PR will be merged. It will be easier for me

**Comment by Cu8eR** [comment]
I would like to finish this into MYBB 1.8.7, I need to merge the WIP PR which adds min to numeric settings. It would be easier for me to follow latest changes in description

**Comment by dequeues** [comment]
This PR has merge conflicts that need to be resolved.

**Comment by Cu8eR** [comment]
@dequeues - Yes, I know. WIP - I had been waiting over 4 months for another PR. I will fix it soon (not at home)

**Comment by Sama34** [comment]
It bugs me that the fields use capitalized first letters but you capitalized all the word. The quotation marks are unnecessary too IMO.

**Comment by Cu8eR** [comment]
I will finish this PR after you merge https://github.com/mybb/mybb/pull/2193 . Because fixing merge conflicts takes a lot of time :(

**Comment by Cu8eR** [comment]
@Sama34 - OK, I agree with you! Thx for your feedback.
@JN-Jones @PaulBender and others MyBB dev - I will create a new PR with fixed conflicts later today. Please review it carefully, I will try my best to find them all and fix the missing descriptions.

**Pull request closed without merging**
