### PR TITLE
Preview usergroup's username style via user-group settings

### PR DESCRIPTION
**Pull request by Pyragon**
This was useful for me when I was editing or adding a usergroup. 
Before I was adding a test account to the groups to double check the username styles every time.

### CODE REVIEW

**Comment by Cu8eeeR** [comment]
Why not, I like it! Useful .)

**Comment by Shade-** [comment]
Seems useful. If no one opposes the PR I will merge this. @mybb/developers @mybb/sqa.

**Comment by Pyragon** [comment]
Done. Thank you

**Comment by Shade-** [comment]
Thank you. I'm going to wait a reply from other members and eventually merge it.

**Comment by euantorano** [comment]
Looks good to me, quite a useful addition IMO.

**Pull request merged**
