### PR TITLE
[New Feature MyBB 1.8] Include delete function for plugins

### PR DESCRIPTION
**Pull request by SvePu**
https://community.mybb.com/thread-234750.html

This new feature includes the possibility to delete plugins from plugin overview in ACP.

You can implement this function by create a new plugin function e.g. `myplugin_delete()`

In this function you have to return an `array()` of plugin files or to delete only the main plugin file a bool `true`.
Alias `{lang}` gets all translation of plugin language files.

E.g.:
``` php
myplugin_delete()
{
	return array(
		'inc/languages/{lang}/myplugin.lang.php',
		'inc/languages/{lang}/admin/myplugin.lang.php',
		'inc/plugins/myplugin.php'
	);
}
```
or
``` php
myplugin_delete()
{
	return true; // Only main plugin file will be deleted
}
```

### CODE REVIEW

**Comment by Eldenroot** [comment]
This is great! It could save a lot of time for admins - no more deleting files one by one manually :) Thank you!

**Comment by SvePu** [comment]
@Eldenroot Thanks and yes, it would be nice to have but I guess it won't be integrated because focus is on MyBB 1.9.

**Comment by Eldenroot** [comment]
@SvePu - maybe, but 1.8 will be still here :) I hope that somebody from mybb dev team will merge opened PRs and release 1.8.30 sooner than later!

**Comment by yuliu** [comment]
Seems the PR is messed as of now.

If you didn't intended to fix #4713 in this PR, I think you could just hard reset your local branch to commit https://github.com/mybb/mybb/pull/4516/commits/ffb81f5ca90645c3f0e8bd9190cbda07f36464e9 and force push it.

**Comment by SvePu** [comment]
@yuliu
You're right ... I'll delete my old fork and fork mybb again to create a new pr.

**Comment by yuliu** [comment]
> @yuliu You're right ... I'll delete my old fork and fork mybb again to create a new pr.

I really think you could try hard reset first, and that'll save you a lot.

`git reset --hard ffb81f5ca90645c3f0e8bd9190cbda07f36464e9`

and then

`git push --force`

Just seen you deleted the fork while typing the above..

**Comment by SvePu** [comment]
@yuliu 
Thank you very much ... next time I'll try your way first.

**Comment by chack1172** [comment]
It is a googd feature, I started implementing it in some of my plugins hooking to deactivate hook and checking for action=destroy. The issue with that is that plugins must be installed to make it work.
This is an example: https://github.com/chack1172/Additional-Files/blob/master/Upload/inc/plugins/additionalfiles.php

**Pull request closed without merging**
