### PR TITLE
Fixes #4293 - "Click to edit" added when post content is empty

### LINKED ISSUE #4293: "Click to edit" added when post content is empty
A _Click to edit_ message is added to posts when their content is empty.

With the [Minimum Message Length](https://github.com/mybb/mybb/blob/mybb_1825/install/resources/settings.xml#L1285-L1293), empty posts may suggest a server-side problem, but the unnecessary client-side message may point in the wrong direction when troubleshooting.

Details: https://community.mybb.com/thread-231510-post-1364051.html

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #4293

### CODE REVIEW

**Comment by Eldenroot** [comment]
Just a note: I will update template versions (due to JS update) once I get the feedback. :)

**Comment by Eldenroot** [comment]
@Sama34 - OK, done!

**Review by Sama34 — APPROVED** [review]
I would like these settings to be defined through the templates, but I'm fine with this fix.

**Comment by Eldenroot** [comment]
I think it is fine... we can avoid adding more template changes for this simple fix.

**Pull request merged**
