### PR TITLE
Update to class_mailhandler.php (fixes #2883)

### LINKED ISSUE #2883: SMTP mailhandler should use the from name
The SMTP mailhandler doesn't currently use the `FROM` command to set the from name for emails sent (though the PHP mail handler does).

Originally reported here: https://community.mybb.com/thread-213661.html

### PR DESCRIPTION
**Pull request by fluxtion**
Due to my general GitHub noobishness, I ended up fixing 3 issues in one PR so this is a carbon copy without the other fixes.

### CODE REVIEW

**Comment by fluxtion** [comment]
@kawaii Can you be my tester again please? This works so I'd like to see it merged. :)

**Comment by kawaii** [comment]
Confirmed this one at the start of the year but forgot to mark it as such. @euantorano will the new SwiftMailer stuff we're sneaking into 1.9 have any effect on or conflict with this at all? If not provided you're happy I guess we can merge.

**Comment by fluxtion** [comment]
Thanks :)

**Comment by euantorano** [comment]
@kawaii I might have to modify the SwiftMailer branch slightly, but I still need to finish work on that anyway so I'm happy to merge this now you've confirmed it works.

**Pull request merged**
