### PR TITLE
Fix #1773

### LINKED ISSUE #1773: Avatars pushed to CDN are not resized
http://community.mybb.com/thread-165704.html

This is likely an issue with order of processing. Will have to look into the cause.

### PR DESCRIPTION
**Pull request by euantorano**
Copy scaled avatar image to CDN.

### CODE REVIEW

**Comment by Sama34** [comment]
Can somebody with an CDN up confirm this does works?

**Comment by Cu8eR** [comment]
I think this should be in 1.8.4 - this "bug" has a side effect on site´s performance

**Comment by Sama34** [comment]
I suppose we should trust @euantorano on this one since he seems to be the only one with the proper setup for this kind of tests.

**Comment by Cu8eR** [comment]
I agree

**Comment by PaulBender** [comment]
Looks good.

**Pull request merged**
