### PR TITLE
Fixes #2497 - Missing lang string for "time" in moderation

### LINKED ISSUE #2497: Delayed moderation - missing lang string for time
https://community.mybb.com/thread-203431.html

Anyway. the lang string is here... am I right? 
https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L8010

### PR DESCRIPTION
**Pull request by Cu8eeeR**
Fixes #2497 - Missing lang string for "time" in moderation

### CODE REVIEW

**Comment by JN-Jones** [comment]
This would fix the issue. Need to take a look whether it's probably better to put it in the global file but this should fix the issue.

**Comment by Cu8eeeR** [comment]
I think it is enought, anyway no problem to edit my PR

**Comment by JN-Jones** [comment]
@Ben-Conway can you take a look at this?

**Comment by Ben-Conway** [comment]
Looks like I got beat to it.

**Pull request merged**
