### PR TITLE
Fixes #4395

### LINKED ISSUE #4395: Extra "dots" in global.lang.php
Regression from this PR #4287

### PR DESCRIPTION
**Pull request by Eldenroot**
#4395

Resolves #4395

### CODE REVIEW

**Comment by Sama34** [comment]
Is there a community report on this ? The former issue adds no extra "dots" and I don't see them in the code.

**Comment by lairdshaw** [comment]
> Is there a community report on this ? The former issue adds no extra "dots" and I don't see them in the code.

Without wishing to speak for @Eldenroot, I think he simply means that compared to the equivalent messages above those two - unapproved_thread, unapproved_threads, unapproved_post, unapproved_posts, unapproved_attachment, and unapproved_attachments - those two messages that were added in that prior issue were added so as to end in a full stop, but, for consistency, they should not end in a full stop, given that those equivalent messages don't. Hence, he removed the full stops. Seems legit to me.

**Comment by Sama34** [comment]
The `mod_notice` language string adds the full stop or period for these messages you suggest :
https://github.com/mybb/mybb/blob/e462060b47fff996f2156cd2dc13046e0c419a29/inc/languages/english/global.lang.php#L326

However, the language strings related to this issue are rendered differently :
(Full stop or period is neither added in the `groupleader_notice` language string nor the `global_pending_joinrequests` template.)
https://github.com/mybb/mybb/blob/e462060b47fff996f2156cd2dc13046e0c419a29/inc/languages/english/global.lang.php#L335
https://github.com/mybb/mybb/blob/e462060b47fff996f2156cd2dc13046e0c419a29/install/resources/mybb_theme.xml#L4208

Below an attached preview from the community forums :
image

Thus, this PR is actually removing the full stop or period, which would make it inconsistent with other similar messages.

Otherwise, I can't see the _extra_ (2 or more) dots that the issue implies.

**Comment by lairdshaw** [comment]
Thanks for the in-depth analysis. I take back that "seems legit". I now think we should close this PR and its associated issue.

**Comment by Sama34** [comment]
@Eldenroot if you think we misunderstood don't hesitate into correcting us please.

**Comment by Eldenroot** [comment]
OK guys, np :)

**Pull request closed without merging**
