### PR TITLE
Remove attachment Text BBcode into Post

### LINKED ISSUE #3644: Remove attachment Text BBcode into Post
Remove attachment Text BBcode into Post

When Edit a post can delete or add attachment  and can -Insert into a Post -

but When Remove attachment... The BBCode  - Insert into a Post -  Still in the Post!

Reproduction steps
1. Create a post with attachment.
2. Add Attachment.
3. - Insert into a Post -  Buton BBCode
4. Post Reply.

Issue:
When Delete the Attachment  The BBCode -Insert into a Post -  Still in the Post!

- It would be good to delete the BBcode from the Post too!

it's just a suggestion... The Software its Amazing!

Thank you!  :)

Original thread: [Remove attachment Text BBcode into Post](https://community.mybb.com/thread-222217.html)

### PR DESCRIPTION
**Pull request by veryard**
resolves #3644

https://community.mybb.com/thread-222217.html

### CODE REVIEW

**Comment by effone** [comment]
You should use the API as specified in the documentation without messing with source HTML.

Something like this should work:
```
            var instance = $('#message').sceditor('instance');
            if(instance.sourceMode())
            {
                instance.setSourceEditorValue(instance.getSourceEditorValue(false).split('[attachment=' + aid + ']').join(''));
            } else {
                instance.setWysiwygEditorValue(instance.getWysiwygEditorValue(false).split('[attachment=' + aid + ']').join(''));
            }
```

**Comment by Eldenroot** [comment]
@effone and @veryard please could someone of you finish this PR?

**Comment by effone** [comment]
I said what I felt right.

**Comment by Ben-MyBB** [comment]
@veryard Do you plan on completing the PR with the changes?

**Comment by Eldenroot** [comment]
@effone please can you make a new PR with your solution above? I would like to get this into 1822, thank you!

**Comment by veryard** [comment]
@Eldenroot I will get to to this tonight. 

Thanks.

**Comment by veryard** [comment]
https://github.com/mybb/mybb/pull/3816

**Pull request closed without merging**
