### PR TITLE
Fixes #2616 GO button in portal search not inline

### LINKED ISSUE #2616: GO button in portal search not inline
The GO button in portal search should be in a line with the <input> textfield.

Now:
mybb_portal_search_1

After fix:
mybb_portal_search_2

### PR DESCRIPTION
**Pull request by SvePu**

### CODE REVIEW

**Comment by SvePu** [comment]
#2616

**Comment by SvePu** [comment]
Changed template and CSS version to 1811

**Comment by SvePu** [comment]
@Stefan-ST Changed template and CSS version to 1811

**Comment by katosdev** [comment]
Thank you for your contribution. I have informed our developers of your changes and they will get back to you shortly.

**Comment by SvePu** [comment]
@Stefan-ST - Required changes already done ;)

**Pull request merged**
