### PR TITLE
Fixes #2335 php_warnings template not cached globally

### LINKED ISSUE #2335: php_warnings template not cached globally
As the title says.

EDIT: similarly `postbit_profilefield_multiselect_value` and `postbit_profilefield_multiselect` (+ possibly other field templates) in showthread.

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2335

### CODE REVIEW

**Comment by Cu8eeeR** [comment]
Code looks fine (at least for me at the first look), just need to resolve merge conflict

**Comment by PaulBender** [comment]
Conflicts resolved

**Comment by euantorano** [comment]
Thanks, I'll try and double check this this week.

**Comment by Cu8eeeR** [comment]
Tested, works fine @euantorano and others.

**Pull request merged**
