### PR TITLE
Fixes #1704 Banned IPs not being blocked

### LINKED ISSUE #1704: Banned IPs not being blocked
I just got a new user registration from an IP address that is in my blocked list. Also last known IP is also in the blocked list. I am using wild cards to block both IPs such as 103.230.105.*. Yet it still allowed registration to go through. Is 1.6 block list not working with 1.8?

Original thread: [Banned IPs not being blocked](http://community.mybb.com/thread-161124.html)

### PR DESCRIPTION
**Pull request by Stefan-ST**
Fixes #1704

### CODE REVIEW

**Comment by PirataNervo** [comment]
I can feel @Stefan-ST's pain. What about allowing IPv4 ranges but disallow IPv6 and note that in the description?

**Comment by Sama34** [comment]
Din't somebody commented in the community, that `1.*.*.*` will do what `1.*` does? That is enough IMO.

**Comment by Destroy666x** [comment]
I don't think it's enough if people who are upgrading added a lot of `1.*` ranges which will stop working in 1.8. I still hope it will be fixed for IPv4 at least. Shouldn't be too hard I guess - check if the IP is IPv6, the if it is use the new code and if it's not, use the old `preg_match()` code from 1.6: https://github.com/mybb/mybb/blob/master/inc/functions.php#L5540

**Comment by Sama34** [comment]
Oh so it breaks backwards compatibility, sorry didn't noted that in the discussion. Can't those be updated in the upgrade process?

**Comment by Stefan-ST** [comment]
1.* should work now

**Comment by Destroy666x** [comment]
Looks good now.

**Pull request merged**
