### PR TITLE
Fixes #268

### LINKED ISSUE #268: User ratings not merging when account is merged
> When two accounts are merged and they both left a rating on a thread, their rating will duplicate.  
> This is an example from [http://hackforums.net](http://hackforums.net)
> 
> 
> 
> As you can see, the member got banned, and his account got merged.

Original report: http://dev.mybb.com/issues/1524
Reporter: Arnaud C.
Status: Confirmed

### PR DESCRIPTION
**Pull request by WildcardSearch**
Fixes #268

### CODE REVIEW

**Comment by Shade-** [comment]
Looks good from a quick look at the code. I will test this and report eventual issues within 1 day.

**Comment by WildcardSearch** [comment]
Great. Thanks @Shade-!

**Comment by WildcardSearch** [comment]
Good catch, @Shade- 

I'll take care of this today.

**Comment by WildcardSearch** [comment]
That should do it, I think, @Shade- 👍

**Comment by Shade-** [comment]
Tested, working fine. Merging.

**Pull request merged**
