### PR TITLE
Fix #1828 video/images SCEditor permissions and #2396 editor object variable

### LINKED ISSUE #1828: Videos and images forum settings not respected by SCEditor
If you disable videos/images in a forum, they can still be used in SCEditor.

The solution is simple - pass these 2 forum settings as parameters just like it's done with smilies.

EDIT: same applies to signatures (images) and PMs (images and videos) controlled by settings.

### PR DESCRIPTION
**Pull request by Destroy666x**
Added proper permission checks and a hook for easy toolbar edition (also in ACP). Also fixed wrong forum conditions in editpost.php BTW.
https://github.com/mybb/mybb/issues/1828

Added a way to change the default object variable in case there are e.g. multiple editors with different permissions on one page.
https://github.com/mybb/mybb/issues/2396

Not fully tested yet.

### CODE REVIEW

**Comment by JN-Jones** [comment]
@Destroy666x What's the status of this apart from the conflicts?

**Comment by JN-Jones** [comment]
These changes look good to me. If @Destroy666x doesn't reply within this week I'm going to take this over and fix the conflicts so that we can test it and hopefully include it in 1.8.9

**Comment by Ben-Conway** [comment]
@JN-Jones Are you going to take it over?

**Comment by JN-Jones** [comment]
Unfortunately hadn't time but considering that we plan to update SCE and other 3rd party libraries in 1.8.10 this PR probably fits better there as we need to change most SCE related files.

**Pull request closed without merging**
