### PR TITLE
Fixes #2183 subscriptionkey unnececary?

### LINKED ISSUE #2183: subscriptionkey unnececary?
Hello!
As far as I searched (github search function), the subscriptionkey isn't validated when unsubscribing from a topic. Whats the usage of subscriptionkeys at all?

Thanks in advance ...
Thomas131

Original thread: [subscriptionkey unnececary?](http://community.mybb.com/thread-175893.html)

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2183

### CODE REVIEW

**Comment by JN-Jones** [comment]
Looks good though I hadn't time to test it yet.

**Comment by JN-Jones** [comment]
@PaulBender another conflict with the upgrade file

**Comment by PaulBender** [comment]
Conflicts resolved

**Comment by Cu8eR** [comment]
Now it looks good

**Comment by Destroy666x** [comment]
Noticed no problems.

**Pull request merged**
