### PR TITLE
Fixes #2340 - usercp_editlists_user

### LINKED ISSUE #2340: usercp_editlists_user - wrong lang string in title
usercp_editlists_user - wrong lang string in title of the image

`delete}]"  alt="{$lang->remove_from_list}" style="vertical-align: middle;" />`

should be:
`remove_from_list}"  alt="{$lang->remove_from_list}" style="vertical-align: middle;" />`

### PR DESCRIPTION
**Pull request by Cu8eR**
Fixes #2340 - usercp_editlists_user - wrong lang string in title

### CODE REVIEW

**Comment by Destroy666x** [comment]
Why is it wrong though? It shows as "[Delete]" for me.

**Comment by Cu8eR** [comment]
@Destroy666x - I can remove hardcoded "[]" but it should use lang string for - remove user from the buddy list, not just "delete". It is not complete. Alt uses right string, title not.

**Comment by Stefan-ST** [comment]
I'd probably remove the brackets.

**Comment by Cu8eR** [comment]
@Stefan-ST @Destroy666x - I fixed my PR

**Comment by Destroy666x** [comment]
I don't really see how "Delete" is incomplete - it says quite clearly what the button does. But you're right the other one is more suitable, so nothing against the change.

**Pull request merged**
