### PR TITLE
Fixes #1056 - Replace hardcoded lang strings

### LINKED ISSUE #1056: ACP: Replace hardcoded placeholder language string with an actual language variable
There are a few areas in the ACP that still use a hardcoded English language string for the selectable fields placeholder instead of an actual language variable.

I have pinpointed the following locations which need to be fixed:
- [x] Forum Management -> Moderators -> Add User as Moderator (admin/modules/forum/management.php line 2632)
- [x] Users & Groups -> Find Users -> Username contains (admin/modules/user/users.php line 4074)
- [x] Users & Groups -> Merge Users -> Source and Destination Account (admin/modules/user/users.php lines 2083, 2113)
- [x] Users & Groups -> Banning -> Banned Accounts (admin/modules/user/banning.php line 564)

### PR DESCRIPTION
**Pull request by Cu8eR**
Fixes #1056 - ACP: Replace hardcoded placeholder language string with an actual language variable

WIP!

### CODE REVIEW

**Comment by Cu8eR** [comment]
MyBB Devs - I cannot find more, any hints?

**Comment by dequeues** [comment]
I can't seem to find anymore. @mybb/sqa

**Comment by Cu8eR** [comment]
If nothing more, please merge it in your free time. Thank you

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/blob/feature/admin/jscripts/themes.js#L185

**Comment by Cu8eR** [comment]
@Destroy666x - thank you!

**Comment by Destroy666x** [comment]
I don't remember/see any other, I guess it can be merged if noone else knows. And for the mentioned select2 another issue could be opened since I remember something similar in the bug reports forum.

**Pull request merged**
