### PR TITLE
Fix #4468: Collapsible.init() should be expandables.init()

### LINKED ISSUE #4468: Collapsible.init() should be expandables.init() in jscripts/general.js
This causes an error which can be seen in the console.

Probably, this was due to a mistake of mine during rebasing. I haven't investigated carefully as the fix is very straightforward.

### PR DESCRIPTION
**Pull request by lairdshaw**
Resolves #4468.

### CODE REVIEW

**Comment by Matslom** [comment]
The expandables feature need more work for 1.9. There were some changes in class naming in new theme and after rebase, there are pointing to theme from 1.8.
Looking at diff of 215ac5f5cee9b26a56111d7843afb19d28a693cc
image
Class names need some fixes.

**Comment by lairdshaw** [comment]
Is this something you can help with, @Matslom? I was kind of "rebasing blind" here, so if you have a deeper understanding of this area of the code, I would greatly appreciate your fix.

**Comment by Matslom** [comment]
@lairdshaw I don't have permissions to push commits in others PR's, so I created new PR #4491

**Comment by lairdshaw** [comment]
Superseded by @Matslom's PR #4491 linked to above and now merged: closing this PR.

**Pull request closed without merging**
