### PR TITLE
fixes #2087 broken task manager URL

### LINKED ISSUE #2087: 404 cron documentation not found
I try to schedule a weekly backup.
via [tools &amp; maintenance] [task manager]  I select [weekly backup]
when I click [save and finish] I get a screen:

"The selected task has been updated successfully.

WARNING: You are about to enable a task that is only meant to be run via cron (Please see the MyBB Docs for more information). Continue?"

when I click on the link -MyBB Docs- , I get a 404 error.

I use 1.8.5

Original thread: [404 cron documentation not found](http://community.mybb.com/thread-172405.html)

### PR DESCRIPTION
**Pull request by andrewjs18**

### CODE REVIEW

**Comment by Cu8eR** [comment]
#2087

**Comment by Destroy666x** [comment]
Will you fix other links in this PR or is this ready to merge?

**Comment by andrewjs18** [comment]
@Destroy666x, if I can get the other pages done, then I'll add them to this PR, but you can merge it if you'd like...doesn't matter to me.

**Comment by andrewjs18** [comment]
@Destroy666x, I did a separate pull request to fix more URLs: https://github.com/mybb/mybb/pull/2453

**Pull request merged**
