### PR TITLE
Simple search : unable to search some specific string (start by and)

### PR DESCRIPTION
**Pull request by Eldenroot**
https://community.mybb.com/thread-235334.html

Please test

Resolves #ISSUE_ID

### CODE REVIEW

**Comment by Eldenroot** [comment]
Or maybe we can try this method:
https://github.com/Destroy666x/mybb/commit/565262fd358228357f33cf4f7b4cd8f98282a246

**Comment by Eldenroot** [comment]
Any feedback from devs?

**Comment by Eldenroot** [comment]
Devs? Please some feedback or close this one :)

**Comment by Eldenroot** [comment]
Any feedback?

**Comment by lairdshaw** [comment]
> Or maybe we can try this method: [Destroy666x@565262f](https://github.com/Destroy666x/mybb/commit/565262fd358228357f33cf4f7b4cd8f98282a246)

That method has been implemented in PR #4707, which I think makes this PR redundant.

**Pull request closed without merging**
