### PR TITLE
Fixes #1939 format_avatar caching issue

### LINKED ISSUE #1939: format_avatar caching issue
The format_avatar function caches the avatar on the first call. However the cache doesn't consider the max_dimensions parameter. Eg I use the function sometimes with a max dimension of "17x17" to display the avatar in a text, however on a page where the function is called before without (or with different) max dimensions the cache will contain the bigger image and return it which breaks my complete text.

Original thread: [format_avatar caching issue](http://community.mybb.com/thread-164490.html)

### PR DESCRIPTION
**Pull request by JN-Jones**
#1939 @Destroy666x @euantorano

### CODE REVIEW

**Comment by euantorano** [comment]
Looks good to me :+1:

**Comment by Destroy666x** [comment]
A nice solution, but it doesn't work because there is a typo - `$key = $dimensions;` should be `$key = $max_dimensions;`

**Comment by JN-Jones** [comment]
Why should it use the max dimensions and not the actual dimensions? `$dimensions` is used to resize the avatar.

**Comment by Destroy666x** [comment]
Because the dimensions provided in funciton parameter are always the same for the same avatar image, so the fix doesn't work. Just test it - this is after applying `$key = $dimensions`: http://nooo.hol.es/mybb16/showthread.php?tid=12 After changing what I said the log avatars have correct 40x40.

**Comment by JN-Jones** [comment]
That forum is password protected.

Anyways, your change doesn't make any sense and instead would reintroduce the error again. Eg calling the function without a max dimension or with the same max dimension but with different dimensions wouldn't work. It sounds more like the showthread calls the function in a wring way. I'll take a look at showthread tomorrow but caching the max dimension is definitely the wrong way.

**Comment by Destroy666x** [comment]
Password is test

**Comment by Destroy666x** [comment]
> It sounds more like the showthread calls the function in a wring way.

Nope, same thing happens everywhere. For example profile: http://nooo.hol.es/mybb16/member.php?action=profile&uid=4 The 4 avatars should be max 30x30.

> calling the function without a max dimension

The default max dimension setting mentioned above would be used then.

> or with the same max dimension but with different dimensions 

This is indeed a problem, but I don't see a case where the same avatar image (so image with the same path) would have different dimensions. Is that even technically possible? Of course different

**Comment by JN-Jones** [comment]
Hmm, I see where the issue is. Need to check something tomorrow to see what the best fix is.

**Comment by JN-Jones** [comment]
The issue is that you can call the function in two ways:
- `format_avatar($user['avatar'], $user['avatardimensions'], '16x16');`
- `format_avatar($user['avatar'], '16x16');`
While the first is how the function is designed and how it's called in the core the second is used in some plugins (including @euantorano's and mine). Though that disables the scalling we should avoid breaking plugins and therefor I've changed the cache to `$avatars['avatar']['dimensions']['max_dimensions']` which should work in all cases.

**Comment by Destroy666x** [comment]
Looks good now.

**Comment by Destroy666x** [comment]
But now that `$key` is still reserved for `$dimensions`, I think another fallback should be added for `$max_dimensions` in case both the setting and parameter are empty too.

**Comment by JN-Jones** [comment]
`$max_dimensions` should never be empty:
```php
	if(!$max_dimensions)
 	{
		$max_dimensions = $mybb->settings['maxavatardims'];
 	}
```

So using `$max_dimensions` as key shouldn't be a problem.

`$dimensions` on the other hand can be empty (eg if you only want the correct avatar url without any dimensions) and therefor can't be used as key directly.

**Comment by Destroy666x** [comment]
It can be empty. Just look at the setting's description: https://github.com/mybb/mybb/blob/feature/install/resources/settings.xml#L1128 `If this is left blank then there will be no dimension restriction.`

**Comment by Destroy666x** [comment]
But as I see that either the description is misleading for admins or `format_avatar()` lacks checks for that case: https://github.com/JN-Jones/mybb/blob/feature/inc/functions.php#L3041
Should be:
```php
if($max_dimensions && $dimensions[0] > $max_width || $dimensions[1] > $max_height)
```
Otherwise if the 3rd argument is blank and the setting is blank, avatars aren't displayed at all.

**Comment by JN-Jones** [comment]
Missed that comment and only looked at the source. Added the check and `$key2` to avoid the empty key issues.

**Pull request merged**
