### PR TITLE
Fixes #2069 - Search container width

### LINKED ISSUE #2069: Search by Username container width
Goto search.php, under search by username first enter any username which has less characters... now click on the arrow again to search another user, the drop down and the input box has width equal to the already selected username, making it difficult to pick a new user from the drop down....

its because of the foll. css rule in select2.css... imho, it would be better to define a fixed width, say 100px rather than auto...

Code:
.select2-container .select2-choice &gt; .select2-chosen {width: auto;}

Original thread: [Search by Username container width](http://community.mybb.com/thread-167249.html)

### PR DESCRIPTION
**Pull request by Cu8eR**
Fixes #2069 - Search container width

### CODE REVIEW

**Comment by Cu8eR** [comment]
@mmadhankumar

**Comment by Destroy666x** [comment]
I haven't tested it yet, but it's definitely not finished due to no `ver` change.

**Comment by Cu8eR** [comment]
@Destroy666x - ver number should be fixed now

**Comment by Destroy666x** [comment]
The solution seems to be fine, but the new code should be separated somehow (check for reference: https://github.com/mybb/mybb/issues/2199#issuecomment-141424586).

**Comment by Cu8eR** [comment]
@Destroy666x - fixed, please could you check my other PRs (NOT #2303 and #2304) in your free time? I need to clean up my patches in my fork before I start with new ones. Thanks, have a nice day. If anything, tell me.

**Comment by Destroy666x** [comment]
I meant wrapping the modification itself (`min-width: 120px`), not the whole selector. The point is to set it apart from the default 3rd part code.

**Comment by Cu8eR** [comment]
@Destroy666x - OK, you are right. I changed my PR. Is it ok now or I missunderstood you again?

**Comment by Destroy666x** [comment]
Yes, thanks.

**Pull request merged**
