### PR TITLE
Fix #3851 User CP -> pagination in Attachments is broken

### LINKED ISSUE #3851: User CP -> pagination in Attachments is broken
I have 21 pages of attachments in my UCP -> Attachments

However last 3 pages (19, 20, 21) are empty, no attachment is displayed... Also statistics are empty for these pages (this is fine, but the statistci should be counted for all attachments together, not just for one page...)

image

### PR DESCRIPTION
**Pull request by demtor**
Resolves #3851 + optimization that may most of the time save a query

### CODE REVIEW

**Comment by Eldenroot** [comment]
No, it is not working properly. When you click to the latest page in attachment -> pagination will be hidden.

Moreover the statistic window below the pagination is still broken -> it should display values for all attachments, not just for the viewed page.

**Comment by Eldenroot** [comment]
More info:
- only last page is broken
- total downloads and bandwith in statistics are broken (counted only for page before the page you are on, for example when you are on page 15, only 1-15 are counted into statistic; all after page 15 is not).

**Comment by demtor** [comment]
My bad lol, should be okay now. Anyway I think that total downloads and bandwidth usage needs a separate issue since I guess is not really a bug but something done on purpose?

**Comment by Eldenroot** [comment]
I dont think so... others values are calculated correctly. Could you please fix it, or at least @euantorano your opinion?

**Comment by euantorano** [comment]
I'd be happy with a separate issue for the bandwidth/total downloads problem.

**Comment by Eldenroot** [comment]
This fix works fine as it is... for the mentioned issue above we should open a new ticket as euan wrote.

**Comment by Sama34** [comment]
Do you have reproduction steps to review this? I couldn't reproduce in my local envioroment.

**Comment by Eldenroot** [comment]
@Sama34 this PR fixes one bug. Anyway I have found the second one, so lets merge this PR and I will open a new ticket, right? @euantorano

**Comment by Sama34** [comment]
I checked this and everything seems to be as before, nothing changed for me and I didn't find the query being saved, so I won't review this but I suppose it is fine by me to merge if someone else reviews is able to test properly.

**Comment by Eldenroot** [comment]
@Sama34 @euantorano @yuliu 

This PR fixes pagination, so one issue fixed. However we need to open a second ticket for wrong statistics calculation

**Pull request merged**
