### PR TITLE
Fixes #2199 - add keepelement to jquery-modal

### LINKED ISSUE #2199: Reputation confirmation modal sometimes remains on the screen in 1.8.6
If two (or more) reputations are given to posts on the same page (without navigating away or refreshing the page), the second reputation confirmation modal does not close and stays on the screen.
I have give more details on the forums: http://community.mybb.com/thread-178564.html

This is caused because in 1.8.6 the following lines are deleted from modal.close function in jquery.plugins.js:

@@ -70,9 +71,6 @@
     close: function() {
       this.unblock();
       this.hide();
-	  // Deletes the element (multi-modal feature: e.g. when you click on multiple report buttons, you will want to see different content for each)
-	  if (!this.options.keepelement)
-		this.$elm.remove();
       $(document).off('keydown.modal');
     },

### PR DESCRIPTION
**Pull request by ATofighi**
#2199 #2221

### CODE REVIEW

**Comment by Destroy666x** [comment]
It works fine, but as always:
- `general.js` version should be bumped in template(s) and several files which load it
- template version should be bumped

**Comment by ATofighi** [comment]
fixed

**Comment by Destroy666x** [comment]
There are 2 more in `admin/inc/class_page.php`

**Comment by ATofighi** [comment]
fixed

**Pull request merged**
