### PR TITLE
AIM Removal

### PR DESCRIPTION
**Pull request by effone**
As [AIM has been discontinued](https://help.aol.com/articles/aim-discontinued); removed all instances of AIM from MyBB ...

### CODE REVIEW

**Comment by Shade-** [comment]
I'd change all the contact fields to Facebook, Twitter, Instagram, Google and Youtube to give a more modern look to profiles.

**Comment by Shade-** [comment]
Alright.

**Comment by Shade-** [comment]
@effone can you rebase the PR to the current codebase? This can then be merged.

**Comment by effone** [comment]
@Shade- I can't. Look at the repo name.

**Comment by Shade-** [comment]
Recreate the PR then. Next time, retain all your repos until merged, thank you.

**Comment by Eldenroot** [comment]
Thats why we need to merge opened PRs one by one to avoid this conflicts... it is waste of time :( I think that these "small" changes can be merged, not need a lot fo testing. Only the "bigger" changes should be opened for the longer time for properly testing by MyBB devs.

**Comment by effone** [comment]
@Eldenroot don't waste your suggestions. I should not comment here but its very easy to say Recreate, but with due respect of @Shade- 's instructions appended with 'thank you' there are ample of issues pending for like 4 years which can be fixed by like deleting a one word condition from a line - no one bothered to create PR til now, but as I am doing it I am being instructed to recreate a PR with 21 modified files. This scenario would not have arrived if the PR got merged in time.

**Comment by Shade-** [comment]
The fact that this PR modified 21 files suggests that a high number of checks should be done to review it. I'd say it's much easier to not delete repositories and rebase them once a conflict kicks in, and just wait for PRs to be reviewed and merged. The last time we merged PRs blindly, even the most simple ones, we had to deploy a hotfix some hours later due to a missing semicolon.

**Pull request closed without merging**
