### PR TITLE
Fixes #3228 PHP 7 Compatibility

### LINKED ISSUE #3228: Arithmetic with strings can cause PHP Warning in polls.php on PHP >= 7.1
I wanted to update a poll but I got the following error:

Quote:Warning [2] A non-numeric value encountered - Line: 694 - File: polls.php PHP 7.1.17 (Linux)

File: Function/polls.php
Line: 694
errorHandler-&gt;error

This is on line 694 of polls.php:

PHP Code:&#36;numvotes&nbsp;=&nbsp;&#36;numvotes&nbsp;+&nbsp;&#36;votes[&#36;i];&nbsp;
Thanks in advance!

Original thread: [Poll](https://community.mybb.com/thread-217800.html)

### PR DESCRIPTION
**Pull request by AndreRl**
Converts $numvotes to integer. Tested with PHP 7.1.

### CODE REVIEW

**Comment by AndreRl** [comment]
Ah I see, thanks @effone haven't been using GH for long 👍

**Comment by Ben-MyBB** [comment]
Did you manage to do any testing of this @effone ?

**Comment by effone** [comment]
Yeah. Tested in PHP 7.2.4 Works fine for me...

But as I said, there are 234 instances of such arithmetic in 50 files throughout MyBB, not sure which one can cause this warning ...

**Comment by euantorano** [comment]
Yeah, that's a lot of instances to check 😆 We'll merge this for now, and will patch any others that crop up.

**Pull request merged**
