### PR TITLE
Enable attachments to be removed quickly using ajax

### PR DESCRIPTION
**Pull request by zygzagZ**
Implemented ajax handling for removing attachments, enabling users to quickly remove multiple attachments.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Great! Better than popup ajax and refreshing the page, it is annoying :( Good job! Anyway, how difficult is to add checkboxes, I am just asking :)

I am going to test this PR, I will let you know if anything. 
P.S. Is there any way to make popups windows "nicer" and use same style for every popup? Now e have at least 3 different layouts... 

image

**Comment by Eldenroot** [comment]
Works fine

**Comment by zygzagZ** [comment]
Where are the 3 different popup types to be seen? I'll see if I can do anything with it.

**Comment by Eldenroot** [comment]
Delete attachment, delete thread/post or make.moderation action.

These should be same as for rate user/report post. 

There was an issue for this on GitHub, I will try to find it

**Comment by Eldenroot** [comment]
I have been testing for over 14 days on my board, no report from any user, is there anyone who can confirm and merge?

**Comment by euantorano** [comment]
I will do so when I get a chance. I've been testing a couple of PRs a day or so.

**Comment by Eldenroot** [comment]
Ok, 30 days without any issue or report by any user on my live board. Quite useful addition, I dont know how I could live without that :)

**Comment by zygzagZ** [comment]
If this works and has no conflicts then why not merge it?

**Comment by euantorano** [comment]
It will be merged, in just doing some testing on it before I do. I don’t like to merge anything I haven’t actually tested.

**Comment by zygzagZ** [comment]
Oh, sorry, I didn't notice your comment. No hurry! :)

**Pull request closed without merging**
