### PR TITLE
Made Post Icons a global toggle

### LINKED ISSUE #3500: Post Icons Toggle
Just following up on the vote we took on this at: https://community.mybb.com/thread-220553.html

The vote was to add a toggle to these in 1.9 so this issue is to track that.

### PR DESCRIPTION
**Pull request by rajat315315**
Resolves #3500

### CODE REVIEW

**Comment by Eldenroot** [comment]
This should get into 1.8 as well...

**Comment by euantorano** [comment]
Yeah, I'd like to see this targeted at `feature` too as it's a relatively minor change that provides a **big** improvement!

**Comment by Eldenroot** [comment]
@rajat315315 - please, can you open another PR for 1.8? Thx!

**Comment by Eldenroot** [comment]
@effone or others - please, could you create a PR for 1.8 as well? @rajat315315 is not responding and this could be a great feature and life saver, thx§

**Comment by rajat315315** [comment]
Done..

**Comment by euantorano** [comment]
#4212 is the 1.8 version, I'm closing this as once merged into 1.8 it'll also get merged into 1.9.

**Pull request closed without merging**
