### PR TITLE
 Incorrect  redirect URL on private networks and localhost

### PR DESCRIPTION
**Pull request by uzbugg**
- adds functionality to validate netbios name or server alias too

### CODE REVIEW

**Comment by euantorano** [comment]
@Devilshakerz SInce you wrote the original \my_validate_url\ function I believe, can you please chime in on this?

**Comment by Shade-** [comment]
@uzbugg can you please solve the conflicts? Also, still waiting for a reply to my question above.

**Comment by Shade-** [comment]
@uzbugg any chance you can solve the conflicts soon? Otherwise, I'd close this and open a new PR.

**Comment by dvz** [comment]
addressing #2693, fixed by #2735

**Pull request closed without merging**
