### PR TITLE
Fix #3889 - quotes for usernames with quotes

### LINKED ISSUE #3889: username with an apostrophe does not parse correctly in quotes
as the title states, if a user has an apostrophe in their username, when someone quotes them, mybb does not parse their username correctly.

clean install of mybb 1.8.22:

Original thread: [username with an apostrophe does not parse correctly in quotes](https://community.mybb.com/thread-226389.html)

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #3889

Uses the suggestion by @JordanMussi in https://github.com/mybb/mybb/pull/3994

Some tests:

| SCEditor Source Mode Input | Source mode value after witching to WYSIWYG and back | Parsed by MyBB correctly? |
| ---- | ---- | ---- |
| ```[quote="euan's test"]double quote[/quote]``` | ```[quote="euan's test"]double quote[/quote]``` | Yes |
| ```[quote=euan]no quote[/quote]``` | ```[quote="euan"]no quote[/quote]``` | Yes |
| ```[quote="euan"]double quote[/quote]``` | ```[quote="euan"]double quote[/quote]``` | Yes |
| ```[quote='euan']single quote[/quote]``` | ```[quote="euan"]single quote[/quote]``` | Yes |
| ```[quote='euan says "hi"']single quote[/quote]``` | ```[quote='euan says "hi"']single quote[/quote]``` | Yes |

### CODE REVIEW

**Comment by JordanMussi** [comment]
All those cases work for me 👍 

Just for others to be aware that a username with both types of quotes won't work as there's no concept of escaping:

|SCEditor Source Mode Input|Source mode value after switching to WYSIWYG and back|Parsed by MyBB correctly?|
|--------------------------|-----------------------------------------------------|-------------------------|
| ```[quote=euan's "dog"]no quote, mixed[/quote]``` | ```[quote='euan's "dog"']no quote, mixed[/quote]``` | No: `euans "dog" Wrote:` instead of `euan's "dog" Wrote:` |
| ```[quote="euan's "dog""]no quote, mixed[/quote]``` | ```[quote='euan's "dog"']no quote, mixed[/quote]``` | No: `euans "dog" Wrote:` instead of `euan's "dog" Wrote:` |
| ```[quote='euan's "dog"']no quote, mixed[/quote]``` | ```[quote='euan's "dog"']no quote, mixed[/quote]``` | No: `euans "dog" Wrote:` instead of `euan's "dog" Wrote:` |

**Comment by euantorano** [comment]
Yeah, usernames with both types of quotes are going to need some further work, at both the parser and editor level.

**Comment by Ben-MyBB** [comment]
@euantorano do you want me to create a seperate issue for that?

**Comment by euantorano** [comment]
> @euantorano do you want me to create a seperate issue for that?

Yes please @Ben-MyBB, that would be great.

**Comment by Ben-MyBB** [comment]
See #4055. Will be testing this PR tonight or tomorrow morning and merge if no issues :)

**Pull request merged**
