### PR TITLE
Fixes #4271 IP Ban list in the ACP no pagination

### LINKED ISSUE #4271: IP Ban list in the ACP no pagination
There is no pagination list in the ACP IP ban list which can lead to a very long page.

Original thread: [IP Ban list in the ACP no pagination](https://community.mybb.com/thread-231396.html)

### PR DESCRIPTION
**Pull request by Starpaul20**
Resolves #4271 

Paging has been added for all three ban filter types.

### CODE REVIEW

**Comment by Eldenroot** [comment]
@PaulBender - good job, in what other places pagination in ACP is missing?

**Comment by Starpaul20** [comment]
Most places in the config section, like Attachment Types, MyCodes, Spiders.

**Comment by Eldenroot** [comment]
Do you plan to open another PRs for these mentioned above (and maybe more?)?. Thx

**Comment by Starpaul20** [comment]
Yes, I intend to do them this weekend (as a new PR).

**Comment by Ben-MyBB** [comment]
We will need to create issues for the other locations

**Comment by euantorano** [comment]
> We will need to create issues for the other locations

Or a tracking issue with checkboxes, which might reduce email SPAM a little.

**Pull request merged**
