### PR TITLE
Fixes #3890 - Forum order - make it wider

### LINKED ISSUE #3890: forum order needs to be wider in admin cp
the forum order is too narrow in the admin cp.  if you have forum orders with 3 numbers, it cuts them off.  

clean install of mybb 1.8.22:

Original thread: [forum order needs to be wider in admin cp](https://community.mybb.com/thread-226390.html)

### PR DESCRIPTION
**Pull request by Eldenroot**
This should be fine, but it depends on your resolution...

Resolves #3890 

image

### CODE REVIEW

**Comment by Sama34** [comment]
Why not a little wider? I now 3 digits seems fair, but we shouldn't be updating this later on.

**Comment by Eldenroot** [comment]
I think 3 digits are more than enough. 

Anyway in 1.9/2.0 there should be a total ACP rewrite

**Comment by Sama34** [comment]
You might be right.

I have no issues leaving it with 3 digits.

**Comment by Eldenroot** [comment]
Please review :)

**Pull request merged**
