### PR TITLE
Detect missing avatar image file and show correct error message

### LINKED ISSUE #4232: Avatar Upload - Wrong Error Message
First disable the "Allow Remote Avatars" option from ACP.

Now go to UCP &gt; Change Avatar : The input field for remote avatar URL will be hidden. Only the local file input will be available.

Don't select any image file to upload, just hit "Change Avatar" button. You will get this error message in place of missing image alert:

Please correct the following errors before continuing:Remote avatar URLs have been disabled by the forum administrator.

Original thread: [Avatar Upload - Wrong Error Message](https://community.mybb.com/thread-230812.html)

### PR DESCRIPTION
**Pull request by effone**
Resolves #4232

### CODE REVIEW

**Comment by dvz** [comment]
We could, alternatively, ignore the request in this case.

**Comment by effone** [comment]
> We could, alternatively, ignore the request in this case.

Thats statement doesn't make a decision. Sir. Let me know what exactly you want and I will change my PR accordingly.

IMO, mal-operation should be intimated that we know you did wrong.

**Comment by dvz** [comment]
The added error may help when `!$_FILES['avatarupload']['name']` (for whatever reason) and remote avatars are disabled, but when they're enabled, it still shows an URL-related error (instead of informing the user that neither method seemed to work, but we don't know which one).
There also seems to be a related, unused string: https://github.com/mybb/mybb/blob/mybb_1824/inc/languages/english/usercp.lang.php#L340 (it can be removed or updated and used to address this),

By not doing anything we can reduce the number of language strings, but either approach seems OK.

**Comment by Ben-MyBB** [comment]
For what it's worth, this approach seems best to me.

**Review by Sama34 — APPROVED** [review]

**Comment by awslabspl** [comment]
> We could, alternatively, ignore the request in this case.

I disagree. It would create confusion amongst less experienced users.

**Comment by euantorano** [comment]
I much prefer an error message to silently failing. This seems like the best approach to me.

**Pull request merged**
