### PR TITLE
Fix enforced case sensitivity check on HEADER's location field

### PR DESCRIPTION
**Pull request by yuliu**
It's a quick fix that should be working.

BTW, seems it's conventional in MyBB to use `#` as the delimiter for PCRE functions, but some outliers use `/`. I'm not sure so I didn't change it.

Source: [community post](https://community.mybb.com/thread-224406.html)

### CODE REVIEW

**Comment by euantorano** [comment]
IMO the regex should also be changed to `^Location:(.*?)(?:\n|$)` to only match headers that are only `Location`, not other headers that end with `Location:`

**Comment by yuliu** [comment]
I think you're right, but can't get it work with `^` right now. I'll try to figure it out. Regex is a trouble to me.

**Comment by euantorano** [comment]
It's likely because the headers string is multi-line, and `^` matches on the start of text, not the start of line by default. Try adding the `m` (multi-line) flag.

**Comment by yuliu** [comment]
Yep, I just figure it out while you're commenting. :tada: 

Oh, seems it should be added with an `m` modifier to enable multi-line mode.

**Comment by yuliu** [comment]
The ending part `(?:\n|$)` seems can be optimized, but I've no idea. Will leave it for MyBB members. :sheep:

**Comment by euantorano** [comment]
The whole thing can probably be optimised a bit, but network requests are already slow anyway.

**Comment by yuliu** [comment]
Fixes #3850.

**Pull request merged**
