### PR TITLE
Fixes #2948 Guest poll voting updates

### LINKED ISSUE #2948: Guest poll voting updates
Currently, if a guest votes in a poll, a cookie is stored on their computer as to what they voted in and for. As this method can be bypassed easily, a better method using IP addresses should be used.

The following changes should be made:
- Add an ipaddress column to the pollvotes table and log the IP of the voter.
- Remove the cookie method of checking for guest votes and instead use the IP address of the guest to check instead.

### PR DESCRIPTION
**Pull request by PaulBender**
Fixes #2948

### CODE REVIEW

**Comment by kawaii** [comment]
Ran into the following error when testing this on MyBB 1.8.14 with PostgreSQL 10.1:
```
SQL Error:
0 - ERROR: invalid byte sequence for encoding "UTF8": 0xac
Query:
INSERT INTO mybb_pollvotes (pid,uid,voteoption,dateline,ipaddress) VALUES ('1','1','1','1516133517','�')
```

**Comment by kawaii** [comment]
Confirmed working with MariaDB 10.2 on MyBB 1.8.14, I'm going to do another PostgreSQL test quickly just to validate that I'm not doing something wrong.

**Comment by euantorano** [comment]
Encodings are a pain in the backside unfortunately. I can't remember if we set the encoding when we startup or not. I'll have a look at this tomorrow and see if I can replicate your issue.

**Comment by PaulBender** [comment]
Try it now. I changed the way poll votes are inserted into the database from its old write_query method to using insert_query/insert_query_multiple method.

**Comment by Ben-MyBB** [comment]
@kawaii

**Comment by kawaii** [comment]
Thanks @PaulBender, your push fixed the issue I was experiencing with PostgreSQL. This is ready to be merged now. I do have one comment however: I voted in a poll using a logged in account, then when logged out I was able to undo the poll vote I had just made (due to the IPs matching of course). Would it not make sense for us to also differentiate between votes made by guests (where we can scrutinize the IP address) and votes made by registered users? In the event where I am using a shared IP address, someone else without a forum account could potentially undo my vote as a guest user without needing to be logged in to my original account. @mybb/developers @mybb/sqa

**Comment by euantorano** [comment]
Good point @kawaii. I definitely think that’s unintended behaviour. If a user has voted from an account, only somebody logged in to that account should be able to reverse it.

**Comment by kawaii** [comment]
Another potential issue I forsee (though personally this is getting a little out of scope) is that multiple guests using the same shared connection would be considered the same user by MyBB. Though I can't honestly see a workaround for that unless you want to start scrutinizing user agents too.

**Comment by PaulBender** [comment]
I added a uid check for guests.

**Comment by kawaii** [comment]
Odd, it seems that the UID check doesn't have the intended effect. As a guest it still displays as though I've already voted but now attempting to undo the vote results in the following error message instead of processing the undo request:
```
You haven't voted in this poll.
```

**Comment by PaulBender** [comment]
I forgot to add the check to the showthread query.

I also changed the undo vote bit to its own variable (something I believed @justinsoltesz complained about).

**Comment by kawaii** [comment]
Great, works as intended now. Thanks @PaulBender! :slightly_smiling_face:

**Pull request merged**
