### PR TITLE
Fixes #4715 - Undefined array key username

### LINKED ISSUE #4715: Undefined array key username
The below reference code can lead to undefined array key username error.

https://github.com/mybb/mybb/blob/bc03b9be63cf2f1c31b672f16d64552e4f0736d7/member.php#L1724

The root cause is that the code is run through irrespective of the result of the check in line 1721.

I would suggest the following fix:

```
$input_username = '';

if(!empty($mybb->input['username']))
{
	$input_username = htmlspecialchars_uni($mybb->input['username']);
}
```

### PR DESCRIPTION
**Pull request by Eldenroot**
Resolves #4715 

Fix proposed by @drecomx

### CODE REVIEW

**Comment by drecomx** [comment]
These lines are obsolete from my point of view:
		if(!isset($mybb->input['username']))
		{
			$input_username = '';
		}

as my suggested fix initialises $input_username to an empty string and populates it with a value if provided in input.

**Review by Sama34 — APPROVED** [review]

**Comment by Sama34** [comment]
Oh, yes, the lines above should be removed as they would become redundant with the provided fix.

**Review by Sama34 — CHANGES_REQUESTED** [review]
Lines 1720-1723 are redundant now.

**Comment by Stefan-MyBB** [comment]
Why not this?
```php
$input_username = htmlspecialchars_uni($mybb->get_input('username'));
```

**Review by Sama34 — APPROVED** [review]

**Pull request merged**
