### PR TITLE
Fix #2594 and #1834 PM's to users with disabled PM's

### LINKED ISSUE #1834: PM disable option
When a user uncheck (during registration or in user CP) this option: "Receive private messages from other users" but some user groups have this permission enabled (checked) "Can check private messages even if recipients have them disable?" - for these groups there is no send PM to a user with disable PMs in his user profile link.

There should be this link, right?

Original thread: [PM disable option](http://community.mybb.com/thread-167101.html)

EDIT: also applies to other places - postbit, managegroups, showteam and maybe more.

### LINKED ISSUE #1837: Setting safe_html to 1 for the parser though it isn't supported
http://crossreference.mybboard.de/nav.html?inc/datahandlers/pm.php.source.html#l660
http://crossreference.mybboard.de/nav.html?inc/datahandlers/post.php.source.html#l1105

Both pass `'safe_html' => 1` as option to the parser, however the parser doesn't have that option at all.

### LINKED ISSUE #2594: Problem Send PM - Member Profile
Hi guys,
today I was watching some profiles of users that are awaiting activation and the language variable of the link is empty. Users in awaiting activation in my forum can't receive/send PMs. Watching the PHP I saw that conditions that set the language and load the template are different, I think that this is the problem.

Original thread: [Problem Send PM - Member Profile](https://community.mybb.com/thread-206936.html)

### PR DESCRIPTION
**Pull request by Matslom**
Fix #2594 
Fix #1834
[PM's links in header are](https://github.com/mybb/mybb/issues/2594#issuecomment-271076005) already fixed in 1.8.9.

### CODE REVIEW

**Comment by Ben-Conway** [comment]
Good work @Matslom 
@Cu8eeeR any chance of you being able to test this?

**Comment by Cu8eeeR** [comment]
@Ben-Conway - I will, later today.

**Comment by Ben-Conway** [comment]
Thanks @Cu8eeeR !

**Comment by Cu8eeeR** [comment]
@Matslom - please, you reffer to incorrect issue, it should be #1834 not #1837

**Comment by Matslom** [comment]
Opps. Fixed, thanks @Cu8eeeR

**Comment by Cu8eeeR** [comment]
@Matslom @Ben-Conway 

I briefly tested and should be all fine and working :) Good job!

**Comment by euantorano** [comment]
The PM button on the postbit still doesn't show for #1834 - see the function `build_postbit` in `inc/functions_post.php`, line `335`.

**Comment by Matslom** [comment]
@euantorano @Cu8eeeR check commit if u can.

**Pull request merged**
